/*
 * Unit tests for src/logic/pathfinding.c
 *
 * Self-contained: redefines minimal type stubs and includes pathfinding.c
 * directly to avoid the heavy types.h include chain (Raylib, sqlite3, biome).
 * Compiles with `make test` using only -lm.
 *
 * Updated for Plan 11-05: lane_generate_waypoints deleted (canonical waypoints
 * are generated by bf_init in battlefield.c). The Player struct stub is minimal.
 * Tests focus on pathfind_step_entity and direction helpers using the
 * Battlefield canonical waypoint interface.
 */

#include <assert.h>
#include <stdio.h>
#include <math.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>

/* ---- Prevent pathfinding.c's includes from pulling in heavy headers ---- */
#define NFC_CARDGAME_TYPES_H
#define NFC_CARDGAME_PATHFINDING_H
#define NFC_CARDGAME_COMBAT_H
#define NFC_CARDGAME_PLAYER_H
#define NFC_CARDGAME_ENTITIES_H
#define NFC_CARDGAME_BATTLEFIELD_H
#define NFC_CARDGAME_BATTLEFIELD_MATH_H

/* ---- Config defines (must match src/core/config.h) ---- */
#define LANE_WAYPOINT_COUNT  8
#define LANE_BOW_INTENSITY   0.3f
#define LANE_JITTER_RADIUS   10.0f
#define PI_F 3.14159265f
#define NUM_CARD_SLOTS 3
#define MAX_ENTITIES 64
#define BOARD_WIDTH  1080
#define BOARD_HEIGHT 1920
#define SEAM_Y       960
#define BASE_NAV_RADIUS 56.0f
#define BASE_DEPOSIT_SLOT_GAP 4.0f
#define BASE_ASSAULT_QUEUE_RADIAL_OFFSET 22.0f
#define COMBAT_BUILDING_MELEE_INSET 30.0f
#define COMBAT_MELEE_GOAL_SLACK_MAX 8.0f
#define COMBAT_PERIMETER_TANGENT_SCALE 0.65f
#define COMBAT_STATIC_TARGET_FLOW_TANGENT_SCALE 0.70f
#define COMBAT_STATIC_TARGET_FLOW_ANGLE_MIN_DEG 10.0f
#define COMBAT_STATIC_TARGET_FLOW_ANGLE_MAX_DEG 20.0f

/* ---- Local steering constants (must mirror src/core/config.h) ---- */
#define PATHFIND_AGGRO_RADIUS             192.0f
#define PATHFIND_AGGRO_HYSTERESIS         32.0f
#define PATHFIND_CANDIDATE_ANGLE_SOFT_DEG 30.0f
#define PATHFIND_CANDIDATE_ANGLE_HARD_DEG 60.0f
#define PATHFIND_CANDIDATE_ANGLE_SIDE_DEG 90.0f
#define PATHFIND_CANDIDATE_ANGLE_ESCAPE_DEG 120.0f
#define PATHFIND_CONTACT_GAP              2.0f
#define PATHFIND_WAYPOINT_REACH_GAP       4.0f
#define PATHFIND_JAM_RELIEF_TICKS         6
#define PATHFIND_ESCAPE_BACKTRACK_STEP_RATIO 0.5f
#define PATHFIND_LANE_DRIFT_MAX_RATIO     0.65f
#define PATHFIND_LANE_LOOKAHEAD_DISTANCE  48.0f
#define PATHFIND_PURSUIT_REAR_TOLERANCE   32.0f
#define PATHFIND_ASSAULT_JAM_RELIEF_TICKS 3
#define PATHFIND_ASSAULT_LATERAL_TOLERANCE_RATIO 1.0f
#define PATHFIND_ALLY_SOFT_OVERLAP_RATIO  0.12f
#define PATHFIND_ALLY_SOFT_OVERLAP_MAX    6.0f
#define PATHFIND_ASSAULT_ALLY_SOFT_OVERLAP_RATIO 0.20f
#define PATHFIND_ASSAULT_ALLY_SOFT_OVERLAP_MAX   8.0f
#define PATHFIND_ASSAULT_SAME_TARGET_SOFT_OVERLAP_BONUS 2.0f
#define PATHFIND_ASSAULT_SAME_TARGET_SOFT_OVERLAP_MAX   10.0f
#define PATHFIND_ASSAULT_CLOUD_SOFT_OVERLAP_SCALE 1.0f
#define PATHFIND_ASSAULT_CLOUD_FLOW_WEIGHT 18.0f
#define PATHFIND_FREE_MOVER_LATERAL_TOLERANCE_RATIO 1.5f

/* ---- Minimal type stubs ---- */
typedef struct { float x; float y; } Vector2;
typedef struct { float x; float y; float width; float height; } Rectangle;

typedef enum { ANIM_IDLE, ANIM_RUN, ANIM_WALK, ANIM_HURT, ANIM_DEATH, ANIM_ATTACK, ANIM_COUNT } AnimationType;
typedef enum { DIR_SIDE, DIR_DOWN, DIR_UP, DIR_COUNT } SpriteDirection;
typedef enum { ESTATE_IDLE, ESTATE_WALKING, ESTATE_ATTACKING, ESTATE_DEAD } EntityState;
typedef enum { TARGET_NEAREST, TARGET_BUILDING, TARGET_SPECIFIC_TYPE } TargetingMode;
typedef enum { ENTITY_TROOP, ENTITY_BUILDING, ENTITY_PROJECTILE } EntityType;
typedef enum { FACTION_PLAYER1, FACTION_PLAYER2 } Faction;
typedef enum { SIDE_BOTTOM, SIDE_TOP } BattleSide;

typedef struct {
    AnimationType anim;
    SpriteDirection dir;
    float elapsed;
    float cycleDuration;
    float normalizedTime;
    bool oneShot;
    bool finished;
    bool flipH;
} AnimState;

typedef struct {
    float prevNormalized;
    float currNormalized;
    bool finishedThisTick;
    bool loopedThisTick;
} AnimPlaybackEvent;

typedef struct { void *texture; int frameWidth; int frameHeight; int frameCount; void *visibleBounds; } SpriteSheet;
typedef struct { SpriteSheet anims[ANIM_COUNT]; } CharacterSprite;

/* Nav profile enum (mirrors src/core/types.h). LANE=0 is the safe default
 * for memset-zero entities, preserving legacy test behavior. */
typedef enum {
    NAV_PROFILE_LANE = 0,
    NAV_PROFILE_ASSAULT,
    NAV_PROFILE_FREE_GOAL,
    NAV_PROFILE_STATIC
} UnitNavProfile;

typedef enum {
    ASSAULT_SLOT_NONE = 0,
    ASSAULT_SLOT_PRIMARY,
    ASSAULT_SLOT_QUEUE
} AssaultSlotKind;

typedef enum {
    DEPOSIT_SLOT_NONE = 0,
    DEPOSIT_SLOT_PRIMARY,
    DEPOSIT_SLOT_QUEUE
} DepositSlotKind;

typedef struct Entity Entity;

struct Entity {
    int id;
    EntityType type;
    Faction faction;
    EntityState state;
    Vector2 position;
    float moveSpeed;
    int hp, maxHP;
    int attack;
    float attackSpeed;
    float attackRange;
    float attackCooldown;
    int attackTargetId;
    TargetingMode targeting;
    const char *targetType;
    AnimState anim;
    const CharacterSprite *sprite;
    int spriteType; // SpriteType enum, but int to avoid pulling in sprite_renderer.h
    float spriteScale;
    float spriteRotationDegrees;
    BattleSide presentationSide;
    int ownerID;
    int lane;
    int waypointIndex;
    float laneProgress;
    float hitFlashTimer;
    bool alive;
    bool markedForRemoval;
    int healAmount;
    float bodyRadius;
    float navRadius;  /* 0 => pathfind_nav_radius falls back to bodyRadius */
    UnitNavProfile navProfile;  /* LANE by default (from memset) */
    int movementTargetId;
    int ticksSinceProgress;
    int lastSteerSideSign;
    int reservedAssaultTargetId;
    int reservedAssaultSlotIndex;
    AssaultSlotKind reservedAssaultSlotKind;
    int reservedDepositSlotIndex;
    DepositSlotKind reservedDepositSlotKind;
};

/* ---- Battlefield stub (minimal for pathfinding) ---- */
typedef struct { Vector2 v; } CanonicalPos;
typedef struct { Vector2 v; BattleSide side; } SideLocalPos;

#define BF_ASSERT_IN_BOUNDS(pos, w, h) \
    assert((pos).v.x >= 0.0f && (pos).v.x <= (w) && \
           (pos).v.y >= 0.0f && (pos).v.y <= (h) && \
           "Entity position outside canonical board bounds")

typedef struct Battlefield {
    float boardWidth;
    float boardHeight;
    float seamY;
    /* Canonical lane waypoints: [side][lane][waypointIdx] */
    CanonicalPos laneWaypoints[2][3][LANE_WAYPOINT_COUNT];
    /* Slot spawn anchors: [side][slot] */
    CanonicalPos slotSpawnAnchors[2][NUM_CARD_SLOTS];
    /* Entity registry -- used by blocker overlap checks in local steering */
    Entity *entities[MAX_ENTITIES * 2];
    int entityCount;
} Battlefield;

/* ---- Stub functions for battlefield API used by pathfinding.c ---- */
BattleSide bf_side_for_player(int playerID) {
    return (playerID == 0) ? SIDE_BOTTOM : SIDE_TOP;
}

CanonicalPos bf_waypoint(const Battlefield *bf, BattleSide side, int lane, int waypointIdx) {
    if (lane < 0 || lane >= 3 || waypointIdx < 0 || waypointIdx >= LANE_WAYPOINT_COUNT) {
        CanonicalPos fallback = { .v = { bf->boardWidth / 2.0f, bf->boardHeight / 2.0f } };
        return fallback;
    }
    return bf->laneWaypoints[side][lane][waypointIdx];
}

CanonicalPos bf_base_anchor(const Battlefield *bf, BattleSide side) {
    CanonicalPos base = { .v = { bf->boardWidth * 0.5f, (side == SIDE_TOP) ? 64.0f : (bf->boardHeight - 64.0f) } };
    return base;
}

BattleSide bf_side_for_pos(CanonicalPos pos, float seamY) {
    return (pos.v.y < seamY) ? SIDE_TOP : SIDE_BOTTOM;
}

bool bf_crosses_seam(CanonicalPos pos, float spriteHeight, float seamY) {
    float halfH = spriteHeight * 0.5f;
    return (pos.v.y - halfH < seamY) && (pos.v.y + halfH > seamY);
}

Entity *bf_find_entity(const Battlefield *bf, int entityID) {
    if (!bf) return NULL;
    for (int i = 0; i < bf->entityCount; i++) {
        if (bf->entities[i] && bf->entities[i]->id == entityID) {
            return bf->entities[i];
        }
    }
    return NULL;
}

const SpriteSheet *sprite_sheet_get(const CharacterSprite *cs, AnimationType anim) {
    if (!cs || anim < 0 || anim >= ANIM_COUNT) return NULL;
    return &cs->anims[anim];
}

/* ---- Stubs for functions pathfinding.c calls ---- */

void entity_set_state(Entity *e, EntityState newState) {
    if (e) e->state = newState;
}

float combat_target_contact_radius(const Entity *target);
float combat_melee_reach_distance(const Entity *attacker, const Entity *target);
float combat_static_target_attack_radius(const Entity *attacker, const Entity *target);
float combat_static_target_occupancy_radius(const Entity *attacker, const Entity *target);
Vector2 combat_static_target_flow_direction(const Entity *attacker, const Entity *target);
float combat_static_target_flow_angle_degrees(const Entity *attacker, const Entity *target);

static bool combat_uses_direct_range(const Entity *attacker, const Entity *target) {
    (void)target;
    return attacker && attacker->healAmount > 0;
}

static unsigned int combat_pair_hash(int attackerId, int targetId) {
    unsigned int x = (unsigned int)attackerId * 1103515245u;
    x ^= (unsigned int)targetId * 2654435761u;
    x ^= x >> 16;
    return x;
}

static Vector2 combat_normalize_or(Vector2 v, Vector2 fallback) {
    float lenSq = v.x * v.x + v.y * v.y;
    if (lenSq <= 0.0001f) return fallback;

    float invLen = 1.0f / sqrtf(lenSq);
    return (Vector2){ v.x * invLen, v.y * invLen };
}

Vector2 combat_static_target_flow_direction(const Entity *attacker, const Entity *target) {
    if (!attacker || !target) return (Vector2){ 0.0f, 0.0f };

    Vector2 inward = {
        target->position.x - attacker->position.x,
        target->position.y - attacker->position.y
    };
    Vector2 ownerFallback = (attacker->ownerID == 1)
        ? (Vector2){ 0.0f, -1.0f }
        : (Vector2){ 0.0f, 1.0f };
    inward = combat_normalize_or(inward, ownerFallback);

    Vector2 tangent = { -inward.y, inward.x };
    float tangentBuckets[] = { -0.95f, -0.55f, -0.2f, 0.2f, 0.55f, 0.95f };
    unsigned int hash = combat_pair_hash(attacker->id, target->id);
    float tangentBucket = tangentBuckets[hash % (sizeof(tangentBuckets) / sizeof(tangentBuckets[0]))];

    return combat_normalize_or(
        (Vector2){
            inward.x + tangent.x * tangentBucket * COMBAT_STATIC_TARGET_FLOW_TANGENT_SCALE,
            inward.y + tangent.y * tangentBucket * COMBAT_STATIC_TARGET_FLOW_TANGENT_SCALE
        },
        inward
    );
}

float combat_static_target_flow_angle_degrees(const Entity *attacker, const Entity *target) {
    if (!attacker || !target) return COMBAT_STATIC_TARGET_FLOW_ANGLE_MIN_DEG;

    unsigned int hash = combat_pair_hash(attacker->id, target->id);
    float t = (float)(hash & 1023u) / 1023.0f;
    return COMBAT_STATIC_TARGET_FLOW_ANGLE_MIN_DEG +
           (COMBAT_STATIC_TARGET_FLOW_ANGLE_MAX_DEG -
            COMBAT_STATIC_TARGET_FLOW_ANGLE_MIN_DEG) * t;
}

bool combat_engagement_goal(const Entity *attacker, const Entity *target,
                            const Battlefield *bf, Vector2 *outGoal,
                            float *outStopRadius) {
    (void)bf;
    if (!attacker || !target || !outGoal || !outStopRadius) return false;
    if (combat_uses_direct_range(attacker, target)) {
        *outGoal = target->position;
        *outStopRadius = attacker->attackRange;
        return true;
    }
    if (target->type == ENTITY_BUILDING || target->navProfile == NAV_PROFILE_STATIC) {
        *outGoal = target->position;
        *outStopRadius = combat_static_target_attack_radius(attacker, target);
        return true;
    }
    *outGoal = target->position;
    *outStopRadius = attacker->bodyRadius + target->bodyRadius + PATHFIND_CONTACT_GAP;
    return true;
}

float combat_target_contact_radius(const Entity *target) {
    if (!target) return 0.0f;
    if (target->type == ENTITY_BUILDING || target->navProfile == NAV_PROFILE_STATIC) {
        float navR = (target->navRadius > 0.0f) ? target->navRadius : target->bodyRadius;
        float combatRadius = navR - COMBAT_BUILDING_MELEE_INSET;
        return (combatRadius > target->bodyRadius) ? combatRadius : target->bodyRadius;
    }
    return (target->navRadius > 0.0f) ? target->navRadius : target->bodyRadius;
}

float combat_melee_reach_distance(const Entity *attacker, const Entity *target) {
    if (!attacker || !target) return 0.0f;

    float contactDistance = combat_target_contact_radius(target) +
                            attacker->bodyRadius +
                            PATHFIND_CONTACT_GAP;
    float slack = attacker->attackRange - contactDistance;
    if (slack < 0.0f) slack = 0.0f;
    if (slack > COMBAT_MELEE_GOAL_SLACK_MAX) slack = COMBAT_MELEE_GOAL_SLACK_MAX;
    return slack;
}

float combat_static_target_attack_radius(const Entity *attacker, const Entity *target) {
    if (!attacker || !target) return 0.0f;
    if (combat_uses_direct_range(attacker, target)) {
        return attacker->attackRange;
    }

    return combat_target_contact_radius(target) +
           attacker->bodyRadius +
           PATHFIND_CONTACT_GAP +
           combat_melee_reach_distance(attacker, target);
}

float combat_static_target_occupancy_radius(const Entity *attacker, const Entity *target) {
    if (!attacker || !target) return 0.0f;

    float attackRadius = combat_static_target_attack_radius(attacker, target);
    if (combat_uses_direct_range(attacker, target)) {
        return attackRadius;
    }

    return attackRadius + attacker->bodyRadius + PATHFIND_CONTACT_GAP;
}

/* ---- Forward declarations for functions in pathfinding.c ---- */
bool pathfind_step_entity(Entity *e, const Battlefield *bf, float deltaTime);
void pathfind_apply_direction(AnimState *anim, Vector2 diff);
BattleSide pathfind_presentation_side_for_position(Vector2 position, float seamY);
void pathfind_sync_presentation(Entity *e, const Battlefield *bf);
void pathfind_commit_presentation(Entity *e, const Battlefield *bf);
void pathfind_update_walk_facing(Entity *e, const Battlefield *bf);
float pathfind_lane_progress_for_position(const Entity *e, const Battlefield *bf, Vector2 position);
void pathfind_sync_lane_progress(Entity *e, const Battlefield *bf);
void pathfind_apply_direction_for_side(AnimState *anim, Vector2 diff, BattleSide side);
float pathfind_sprite_rotation_for_side(SpriteDirection dir, BattleSide side);

/* ---- Include production code under test ---- */
#include "../src/logic/pathfinding.c"

/* ---- Test helpers ---- */

static bool approx_eq(float a, float b, float eps) {
    return fabsf(a - b) < eps;
}

/* Build a Battlefield stub with manually generated straight-line waypoints for
 * both sides. This provides predictable positions for testing pathfinding
 * behavior without depending on bf_init's full logic. */
static Battlefield make_test_battlefield(void) {
    Battlefield bf;
    memset(&bf, 0, sizeof(Battlefield));
    bf.boardWidth = BOARD_WIDTH;
    bf.boardHeight = BOARD_HEIGHT;
    bf.seamY = SEAM_Y;

    float laneWidth = (float)BOARD_WIDTH / 3.0f;
    float bottomSpawnY = 960.0f + 960.0f * 0.8f; /* 1728 */
    float bottomEndY = 192.0f;
    float topSpawnY = 192.0f;
    float topEndY = 960.0f + 960.0f * 0.8f; /* 1728 */

    for (int lane = 0; lane < 3; lane++) {
        float centerX = (lane + 0.5f) * laneWidth;
        for (int wp = 0; wp < LANE_WAYPOINT_COUNT; wp++) {
            float t = (float)wp / (float)(LANE_WAYPOINT_COUNT - 1);
            float bottomY = bottomSpawnY + (bottomEndY - bottomSpawnY) * t;
            float topY = topSpawnY + (topEndY - topSpawnY) * t;
            bf.laneWaypoints[SIDE_BOTTOM][lane][wp].v = (Vector2){ centerX, bottomY };
            bf.laneWaypoints[SIDE_TOP][lane][wp].v = (Vector2){ centerX, topY };
        }
        bf.slotSpawnAnchors[SIDE_BOTTOM][lane] = bf.laneWaypoints[SIDE_BOTTOM][lane][0];
        bf.slotSpawnAnchors[SIDE_TOP][lane] = bf.laneWaypoints[SIDE_TOP][lane][0];
    }

    return bf;
}

static Entity make_test_entity(int lane, int waypointIndex, float moveSpeed) {
    static CharacterSprite testSprite = {
        .anims = {
            [ANIM_IDLE] = { .frameHeight = 64 },
            [ANIM_RUN] = { .frameHeight = 64 },
            [ANIM_WALK] = { .frameHeight = 64 },
            [ANIM_HURT] = { .frameHeight = 64 },
            [ANIM_DEATH] = { .frameHeight = 64 },
            [ANIM_ATTACK] = { .frameHeight = 64 },
        }
    };
    Entity e;
    memset(&e, 0, sizeof(Entity));
    static int s_nextId = 100;
    e.id = s_nextId++;
    e.lane = lane;
    e.waypointIndex = waypointIndex;
    e.moveSpeed = moveSpeed;
    e.state = ESTATE_WALKING;
    e.anim.anim = ANIM_WALK;
    e.anim.dir = DIR_UP;
    e.anim.flipH = false;
    e.sprite = &testSprite;
    e.spriteScale = 1.0f;
    e.presentationSide = SIDE_BOTTOM;
    e.alive = true;
    e.ownerID = 0;  // SIDE_BOTTOM
    e.type = ENTITY_TROOP;
    e.bodyRadius = 14.0f;
    e.attackRange = 50.0f;
    e.movementTargetId = -1;
    e.ticksSinceProgress = 0;
    return e;
}

/* Register a blocker entity with the minimal battlefield stub. Caller owns
 * the storage; this helper just pushes a pointer into the registry. */
static void bf_test_register(Battlefield *bf, Entity *e) {
    bf->entities[bf->entityCount++] = e;
}

static bool test_spawn_pos_overlaps(const Battlefield *bf, Vector2 pos,
                                    float bodyRadius) {
    if (!bf) return false;

    for (int i = 0; i < bf->entityCount; i++) {
        const Entity *other = bf->entities[i];
        if (!other || !other->alive || other->markedForRemoval) continue;
        if (other->type == ENTITY_PROJECTILE) continue;

        float dx = other->position.x - pos.x;
        float dy = other->position.y - pos.y;
        float minDist = bodyRadius + other->bodyRadius + PATHFIND_CONTACT_GAP;
        if (dx * dx + dy * dy < minDist * minDist) return true;
    }

    return false;
}

static bool test_spawn_pos_in_bounds(const Battlefield *bf, Vector2 pos,
                                     float bodyRadius) {
    if (!bf) return false;

    return pos.x - bodyRadius >= 0.0f &&
           pos.x + bodyRadius <= bf->boardWidth &&
           pos.y - bodyRadius >= 0.0f &&
           pos.y + bodyRadius <= bf->boardHeight;
}

static bool test_find_spawn_anchor(const Battlefield *bf, BattleSide side,
                                   int slotIndex, float bodyRadius,
                                   Vector2 *outPos) {
    if (!bf || !outPos || bodyRadius <= 0.0f ||
        slotIndex < 0 || slotIndex >= NUM_CARD_SLOTS) {
        return false;
    }

    static const float lateralMults[] = {
        0.0f, -1.25f, 1.25f, -2.5f, 2.5f, -3.75f, 3.75f, -5.0f, 5.0f
    };
    int lateralCount = (int)(sizeof(lateralMults) / sizeof(lateralMults[0]));
    Vector2 anchor = bf->slotSpawnAnchors[side][slotIndex].v;
    float behindSign = (side == SIDE_BOTTOM) ? 1.0f : -1.0f;

    for (int row = 0; row < 4; row++) {
        float yOffset = behindSign * bodyRadius * (float)row;
        for (int i = 0; i < lateralCount; i++) {
            Vector2 candidate = {
                anchor.x + lateralMults[i] * bodyRadius,
                anchor.y + yOffset
            };
            if (!test_spawn_pos_in_bounds(bf, candidate, bodyRadius)) continue;
            if (test_spawn_pos_overlaps(bf, candidate, bodyRadius)) continue;
            *outPos = candidate;
            return true;
        }
    }

    return false;
}

static void test_step_pack(Entity *pack, int count, Battlefield *bf, int ticks) {
    for (int tick = 0; tick < ticks; tick++) {
        for (int i = 0; i < count; i++) {
            pathfind_step_entity(&pack[i], bf, 1.0f / 60.0f);
        }
    }
}

static int test_spawn_same_lane_pack(Battlefield *bf, Entity *pack, int targetCount,
                                     BattleSide side, int slotIndex, int lane,
                                     int maxTicks) {
    if (!bf || !pack || targetCount <= 0 || maxTicks <= 0) return 0;

    int spawned = 0;
    for (int tick = 0; tick < maxTicks && spawned < targetCount; tick++) {
        Vector2 spawnPos;
        if (test_find_spawn_anchor(bf, side, slotIndex, 14.0f, &spawnPos)) {
            pack[spawned] = make_test_entity(lane, 1, 58.0f);
            pack[spawned].ownerID = (side == SIDE_BOTTOM) ? 0 : 1;
            pack[spawned].position = spawnPos;
            bf_test_register(bf, &pack[spawned]);
            spawned++;
        }

        test_step_pack(pack, spawned, bf, 1);
    }

    return spawned;
}

static float test_pack_total_y(const Entity *pack, int count) {
    float totalY = 0.0f;
    for (int i = 0; i < count; i++) {
        totalY += pack[i].position.y;
    }
    return totalY;
}

static int test_pack_units_at_or_past_waypoint(const Entity *pack, int count,
                                               int waypointIndex) {
    int units = 0;
    for (int i = 0; i < count; i++) {
        if (pack[i].waypointIndex >= waypointIndex) units++;
    }
    return units;
}

/* ---- CORE-01: Canonical waypoints progress toward enemy ---- */
static void test_canonical_waypoints_progress(void) {
    Battlefield bf = make_test_battlefield();

    for (int lane = 0; lane < 3; lane++) {
        /* Waypoints progress toward enemy (Y decreases for SIDE_BOTTOM) */
        for (int i = 1; i < LANE_WAYPOINT_COUNT; i++) {
            assert(bf.laneWaypoints[SIDE_BOTTOM][lane][i].v.y <
                   bf.laneWaypoints[SIDE_BOTTOM][lane][i - 1].v.y);
        }
    }
}

/* ---- CORE-01b: Center lane has consistent lateral position ---- */
static void test_center_lane_consistent_x(void) {
    Battlefield bf = make_test_battlefield();

    float centerX = bf.laneWaypoints[SIDE_BOTTOM][1][0].v.x;
    for (int i = 1; i < LANE_WAYPOINT_COUNT; i++) {
        assert(approx_eq(bf.laneWaypoints[SIDE_BOTTOM][1][i].v.x, centerX, 0.1f));
    }
}

/* ---- CORE-01d: Movement stepping advances waypointIndex ---- */
static void test_movement_step_advances_waypoint(void) {
    Battlefield bf = make_test_battlefield();

    /* Entity starts at waypoint[1] position -- large dt to guarantee overshoot */
    Entity e = make_test_entity(1, 1, 50000.0f);
    e.position = bf.laneWaypoints[SIDE_BOTTOM][1][1].v;

    bool walking = pathfind_step_entity(&e, &bf, 1.0f);
    (void)walking;
    /* Should have advanced past waypoint 1 */
    assert(e.waypointIndex >= 2);

    /* Normal speed: entity moves toward target but doesn't overshoot */
    Entity e2 = make_test_entity(1, 1, 10.0f); /* slow speed */
    e2.position = bf.laneWaypoints[SIDE_BOTTOM][1][1].v;
    /* Move slightly off the waypoint so there's distance to cover */
    e2.position.y += 50.0f;

    int prevIdx = e2.waypointIndex;
    pathfind_step_entity(&e2, &bf, 1.0f / 60.0f);
    /* With slow speed and 50px distance, should still be on same waypoint */
    assert(e2.waypointIndex == prevIdx);
}

/* ---- CORE-01e: Idle at last waypoint ---- */
static void test_idle_at_last_waypoint(void) {
    Battlefield bf = make_test_battlefield();

    /* Place entity near the last segment and step until the continuous lane
     * cursor reaches the lane end. */
    Entity e = make_test_entity(1, LANE_WAYPOINT_COUNT - 1, 50000.0f);
    e.position = bf.laneWaypoints[SIDE_BOTTOM][1][LANE_WAYPOINT_COUNT - 2].v;

    bool walking = true;
    for (int i = 0; i < 8 && walking; i++) {
        walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    }

    /* Should have reached end and transitioned to idle */
    assert(walking == false);
    assert(e.state == ESTATE_IDLE);
    assert(e.waypointIndex >= LANE_WAYPOINT_COUNT);
}

/* ---- CORE-01f: Sprite direction from movement vector ---- */
static void test_sprite_direction(void) {
    AnimState anim;
    memset(&anim, 0, sizeof(AnimState));

    /* Moving left -> DIR_SIDE, flipH=true */
    anim.dir = DIR_UP;
    pathfind_apply_direction(&anim, (Vector2){-100, -10});
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == true);

    /* Moving right -> DIR_SIDE, flipH=false */
    pathfind_apply_direction(&anim, (Vector2){100, -10});
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == false);

    /* Pure vertical movement keeps the right-facing bias */
    pathfind_apply_direction(&anim, (Vector2){0, -100});
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == false);

    /* Same right-facing bias when moving down */
    pathfind_apply_direction(&anim, (Vector2){0, 100});
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == false);

    /* Zero vector: direction unchanged */
    anim.dir = DIR_UP;
    anim.flipH = false;
    pathfind_apply_direction(&anim, (Vector2){0, 0});
    assert(anim.dir == DIR_UP);

    /* Any nonzero X produces DIR_SIDE */
    memset(&anim, 0, sizeof(AnimState));
    pathfind_apply_direction(&anim, (Vector2){-1, -100});
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == true);
}

/* ---- CORE-01g: Perspective-aware vertical direction by owner side ---- */
static void test_sprite_direction_for_side(void) {
    AnimState anim;
    memset(&anim, 0, sizeof(AnimState));

    pathfind_apply_direction_for_side(&anim, (Vector2){100, 0}, SIDE_BOTTOM);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == false);

    pathfind_apply_direction_for_side(&anim, (Vector2){-100, 0}, SIDE_BOTTOM);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == true);

    pathfind_apply_direction_for_side(&anim, (Vector2){0, -100}, SIDE_BOTTOM);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == false);

    pathfind_apply_direction_for_side(&anim, (Vector2){0, 100}, SIDE_BOTTOM);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == false);

    // Top-side sprites still invert flipH so the 180-degree presentation
    // rotation preserves a right-facing bias.
    pathfind_apply_direction_for_side(&anim, (Vector2){0, 100}, SIDE_TOP);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == true);

    pathfind_apply_direction_for_side(&anim, (Vector2){0, -100}, SIDE_TOP);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == true);

    pathfind_apply_direction_for_side(&anim, (Vector2){100, 0}, SIDE_TOP);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == true);

    pathfind_apply_direction_for_side(&anim, (Vector2){-100, 0}, SIDE_TOP);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == false);
}

/* ---- CORE-01ga: Presentation swaps once the entity crosses the seam ---- */
static void test_presentation_side_for_position(void) {
    assert(pathfind_presentation_side_for_position((Vector2){540.0f, 959.0f}, SEAM_Y) == SIDE_TOP);
    assert(pathfind_presentation_side_for_position((Vector2){540.0f, 960.0f}, SEAM_Y) == SIDE_BOTTOM);
    assert(pathfind_presentation_side_for_position((Vector2){540.0f, 1200.0f}, SEAM_Y) == SIDE_BOTTOM);
}

/* ---- CORE-01h: All top-side sprites rotate 180 degrees ---- */
static void test_sprite_rotation_for_side(void) {
    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_SIDE, SIDE_BOTTOM), 0.0f, 0.001f));
    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_UP, SIDE_BOTTOM), 0.0f, 0.001f));
    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_DOWN, SIDE_BOTTOM), 0.0f, 0.001f));

    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_SIDE, SIDE_TOP), 180.0f, 0.001f));
    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_UP, SIDE_TOP), 180.0f, 0.001f));
    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_DOWN, SIDE_TOP), 180.0f, 0.001f));
}

/* ---- CORE-01i: Seam overlap preserves previous presentation side ---- */
static void test_seam_overlap_preserves_presentation_bottom_to_top(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.position = (Vector2){ bf.laneWaypoints[SIDE_BOTTOM][1][4].v.x, 965.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    assert(e.position.y < SEAM_Y);
    assert(e.position.y + 32.0f > SEAM_Y);
    assert(e.presentationSide == SIDE_BOTTOM);
    assert(e.anim.dir == DIR_SIDE);
    assert(e.anim.flipH == false);
    assert(approx_eq(e.spriteRotationDegrees, 0.0f, 0.001f));
}

/* ---- CORE-01j: Fully clear still defers until a walk-loop commit ---- */
static void test_seam_clear_defers_presentation_bottom_to_top(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.position = (Vector2){ bf.laneWaypoints[SIDE_BOTTOM][1][4].v.x, 915.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    assert(e.position.y + 32.0f < SEAM_Y);
    assert(e.presentationSide == SIDE_BOTTOM);
    assert(e.anim.dir == DIR_SIDE);
    assert(e.anim.flipH == false);
    assert(approx_eq(e.spriteRotationDegrees, 0.0f, 0.001f));
}

/* ---- CORE-01k: Walk-loop commit applies bottom-to-top presentation swap ---- */
static void test_walk_loop_commit_swaps_presentation_bottom_to_top(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.position = (Vector2){ bf.laneWaypoints[SIDE_BOTTOM][1][4].v.x, 915.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    pathfind_commit_presentation(&e, &bf);
    pathfind_update_walk_facing(&e, &bf);

    assert(e.presentationSide == SIDE_TOP);
    assert(e.anim.dir == DIR_SIDE);
    assert(e.anim.flipH == true);
    assert(approx_eq(e.spriteRotationDegrees, 180.0f, 0.001f));
}

/* ---- CORE-01l: Seam overlap preserves top-side presentation too ---- */
static void test_seam_overlap_preserves_presentation_top_to_bottom(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.ownerID = 1;
    e.presentationSide = SIDE_TOP;
    e.position = (Vector2){ bf.laneWaypoints[SIDE_TOP][1][4].v.x, 955.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    assert(e.position.y > SEAM_Y);
    assert(e.position.y - 32.0f < SEAM_Y);
    assert(e.presentationSide == SIDE_TOP);
    assert(e.anim.dir == DIR_SIDE);
    assert(e.anim.flipH == true);
    assert(approx_eq(e.spriteRotationDegrees, 180.0f, 0.001f));
}

/* ---- CORE-01m: Fully clear still defers top-to-bottom swap until commit ---- */
static void test_seam_clear_defers_presentation_top_to_bottom(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.ownerID = 1;
    e.presentationSide = SIDE_TOP;
    e.position = (Vector2){ bf.laneWaypoints[SIDE_TOP][1][4].v.x, 1005.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    assert(e.position.y - 32.0f > SEAM_Y);
    assert(e.presentationSide == SIDE_TOP);
    assert(e.anim.dir == DIR_SIDE);
    assert(e.anim.flipH == true);
    assert(approx_eq(e.spriteRotationDegrees, 180.0f, 0.001f));
}

/* ---- CORE-01n: Walk-loop commit applies top-to-bottom presentation swap ---- */
static void test_walk_loop_commit_swaps_presentation_top_to_bottom(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.ownerID = 1;
    e.presentationSide = SIDE_TOP;
    e.position = (Vector2){ bf.laneWaypoints[SIDE_TOP][1][4].v.x, 1005.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    pathfind_commit_presentation(&e, &bf);
    pathfind_update_walk_facing(&e, &bf);

    assert(e.presentationSide == SIDE_BOTTOM);
    assert(e.anim.dir == DIR_SIDE);
    assert(e.anim.flipH == false);
    assert(approx_eq(e.spriteRotationDegrees, 0.0f, 0.001f));
}

/* ---- Phase 3: local steering ---- */

/* Forward progress on a clear lane still advances waypoints. */
static void test_clear_lane_forward_still_advances(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 1, 300.0f);
    e.position = bf.laneWaypoints[SIDE_BOTTOM][1][1].v;

    /* Step many frames to cover the distance to waypoint 2. */
    for (int i = 0; i < 120; i++) {
        pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    }

    assert(e.waypointIndex >= 2);
}

static void test_lane_progress_projection_is_monotonic_off_centerline(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 1, 300.0f);
    unit.position = bf.laneWaypoints[SIDE_BOTTOM][1][1].v;
    pathfind_sync_lane_progress(&unit, &bf);
    float progressAtWp1 = unit.laneProgress;

    unit.position = (Vector2){ unit.position.x + 90.0f, unit.position.y - 120.0f };
    pathfind_sync_lane_progress(&unit, &bf);
    assert(unit.laneProgress > progressAtWp1 + 100.0f);

    float before = unit.laneProgress;
    unit.position = (Vector2){ unit.position.x + 40.0f, unit.position.y + 60.0f };
    pathfind_sync_lane_progress(&unit, &bf);
    assert(unit.laneProgress >= before - 0.001f);
}

static void test_lane_progress_prevents_backtracking_to_stale_waypoint(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 1, 300.0f);
    Vector2 wp2 = bf.laneWaypoints[SIDE_BOTTOM][1][2].v;
    unit.position = (Vector2){ wp2.x + 70.0f, wp2.y - 40.0f };

    Vector2 before = unit.position;
    bool walking = pathfind_step_entity(&unit, &bf, 1.0f / 60.0f);

    assert(walking == true);
    assert(unit.position.y < before.y);
    assert(unit.waypointIndex >= 3);
    assert(unit.laneProgress > pathfind_lane_progress_for_position(&unit, &bf,
                                                                   bf.laneWaypoints[SIDE_BOTTOM][1][1].v));
}

/* A fully blocked steering fan causes the follower to queue in place.
 * Blocked units must not burn through the rest of the lane and transition to
 * IDLE just because they remain jammed for many ticks. */
static void test_blocker_on_waypoint_stays_queued_without_burning_waypoints(void) {
    Battlefield bf = make_test_battlefield();

    Entity follower = make_test_entity(1, 1, 600.0f);
    Vector2 wp = bf.laneWaypoints[SIDE_BOTTOM][1][1].v;
    follower.position = (Vector2){ wp.x, wp.y + 40.0f };

    Entity b_forward = make_test_entity(1, 1, 0.0f);
    b_forward.position = (Vector2){ follower.position.x, follower.position.y - 20.0f };
    b_forward.bodyRadius = 60.0f;

    Entity b_left = make_test_entity(1, 1, 0.0f);
    b_left.position = (Vector2){ follower.position.x - 30.0f, follower.position.y - 10.0f };
    b_left.bodyRadius = 30.0f;

    Entity b_right = make_test_entity(1, 1, 0.0f);
    b_right.position = (Vector2){ follower.position.x + 30.0f, follower.position.y - 10.0f };
    b_right.bodyRadius = 30.0f;

    bf_test_register(&bf, &follower);
    bf_test_register(&bf, &b_forward);
    bf_test_register(&bf, &b_left);
    bf_test_register(&bf, &b_right);

    pathfind_sync_lane_progress(&follower, &bf);
    int prevIdx = follower.waypointIndex;
    float prevProgress = follower.laneProgress;
    Vector2 before = follower.position;
    /* Drive for long enough that the old discrete-waypoint logic would have
     * had many chances to advance stale lane state. */
    for (int i = 0; i < PATHFIND_JAM_RELIEF_TICKS * LANE_WAYPOINT_COUNT; i++) {
        pathfind_step_entity(&follower, &bf, 1.0f / 60.0f);
    }

    assert(follower.state == ESTATE_WALKING);
    assert(follower.waypointIndex == prevIdx);
    assert(follower.laneProgress == prevProgress);
    assert(follower.position.x == before.x);
    assert(follower.position.y == before.y);
}

/* All candidate directions blocked: the unit stays in place and
 * ticksSinceProgress accumulates while jammed. */
static void test_all_candidates_blocked_stays_put(void) {
    Battlefield bf = make_test_battlefield();

    /* Offset the unit off the goal waypoint so goalDist > 0 and the
     * candidate loop actually runs (otherwise the at-goal early-advance
     * path would reset ticksSinceProgress). */
    Entity unit = make_test_entity(1, 1, 300.0f);
    Vector2 wp = bf.laneWaypoints[SIDE_BOTTOM][1][1].v;
    unit.position = (Vector2){ wp.x, wp.y + 40.0f };

    /* Ring the unit with oversized blockers in every candidate direction so
     * no candidate escapes the overlap check. */
    Entity b_forward = make_test_entity(1, 1, 0.0f);
    b_forward.position = (Vector2){ unit.position.x, unit.position.y - 20.0f };
    b_forward.bodyRadius = 60.0f;

    Entity b_left = make_test_entity(1, 1, 0.0f);
    b_left.position = (Vector2){ unit.position.x - 30.0f, unit.position.y - 10.0f };
    b_left.bodyRadius = 30.0f;

    Entity b_right = make_test_entity(1, 1, 0.0f);
    b_right.position = (Vector2){ unit.position.x + 30.0f, unit.position.y - 10.0f };
    b_right.bodyRadius = 30.0f;

    bf_test_register(&bf, &unit);
    bf_test_register(&bf, &b_forward);
    bf_test_register(&bf, &b_left);
    bf_test_register(&bf, &b_right);

    Vector2 before = unit.position;
    int beforeTicks = unit.ticksSinceProgress;

    pathfind_step_entity(&unit, &bf, 1.0f / 60.0f);

    assert(unit.position.x == before.x);
    assert(unit.position.y == before.y);
    assert(unit.ticksSinceProgress == beforeTicks + 1);
}

/* Reaching the last waypoint no longer applies random jitter: position stays
 * exactly at the last waypoint location when snapped. */
static void test_last_waypoint_no_jitter(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, LANE_WAYPOINT_COUNT - 1, 50000.0f);
    /* Start exactly at the last waypoint so one step reaches it. */
    e.position = bf.laneWaypoints[SIDE_BOTTOM][1][LANE_WAYPOINT_COUNT - 1].v;

    Vector2 expected = e.position;
    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);

    assert(walking == false);
    assert(e.state == ESTATE_IDLE);
    /* Position should be at the last waypoint (within epsilon) -- no random offset. */
    assert(fabsf(e.position.x - expected.x) < 0.001f);
    assert(fabsf(e.position.y - expected.y) < 0.001f);
}

/* When movementTargetId is set, the entity steers toward the target center
 * and stops at edge-to-edge contact distance (sum of radii + gap). */
static void test_engagement_goal_stops_at_contact_distance(void) {
    Battlefield bf = make_test_battlefield();

    Entity attacker = make_test_entity(1, 1, 600.0f);
    attacker.position = (Vector2){500.0f, 1500.0f};
    attacker.bodyRadius = 14.0f;

    Entity target = make_test_entity(1, 1, 0.0f);
    target.position = (Vector2){500.0f, 1300.0f};  /* 200 units up */
    target.bodyRadius = 14.0f;
    target.ownerID = 1;  /* enemy */

    attacker.movementTargetId = target.id;

    bf_test_register(&bf, &attacker);
    bf_test_register(&bf, &target);

    /* Step until the attacker stops making progress. */
    for (int i = 0; i < 120; i++) {
        pathfind_step_entity(&attacker, &bf, 1.0f / 60.0f);
    }

    float dx = target.position.x - attacker.position.x;
    float dy = target.position.y - attacker.position.y;
    float dist = sqrtf(dx * dx + dy * dy);
    float expectedContact = attacker.bodyRadius + target.bodyRadius + PATHFIND_CONTACT_GAP;

    /* Attacker stopped at the contact threshold (within one-step tolerance). */
    assert(dist >= expectedContact - 0.5f);
    assert(dist < expectedContact + 12.0f);
}

static void test_jam_relief_shuffles_after_threshold(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 2, 600.0f);
    unit.id = 200;  /* even => prefer left */
    unit.position = (Vector2){ 540.0f, 1400.0f };
    unit.ticksSinceProgress = PATHFIND_JAM_RELIEF_TICKS;

    Entity target = make_test_entity(1, 1, 0.0f);
    target.position = (Vector2){ 540.0f, 1200.0f };
    target.ownerID = 1;
    unit.movementTargetId = target.id;

    Entity blockers[7];
    blockers[0] = make_test_entity(1, 1, 0.0f);
    blockers[0].position = (Vector2){ 540.0f, 1340.0f };              /* forward */
    blockers[1] = make_test_entity(1, 1, 0.0f);
    blockers[1].position = (Vector2){ 510.0f, 1348.0f };              /* left 30 */
    blockers[2] = make_test_entity(1, 1, 0.0f);
    blockers[2].position = (Vector2){ 570.0f, 1348.0f };              /* right 30 */
    blockers[3] = make_test_entity(1, 1, 0.0f);
    blockers[3].position = (Vector2){ 488.0f, 1370.0f };              /* left 60 */
    blockers[4] = make_test_entity(1, 1, 0.0f);
    blockers[4].position = (Vector2){ 592.0f, 1370.0f };              /* right 60 */
    blockers[5] = make_test_entity(1, 1, 0.0f);
    blockers[5].position = (Vector2){ 600.0f, 1400.0f };              /* right 90 */
    blockers[6] = make_test_entity(1, 1, 0.0f);
    blockers[6].position = (Vector2){ 592.0f, 1430.0f };              /* right 120 */

    bf_test_register(&bf, &unit);
    bf_test_register(&bf, &target);
    for (int i = 0; i < 7; i++) {
        bf_test_register(&bf, &blockers[i]);
    }

    Vector2 before = unit.position;
    pathfind_step_entity(&unit, &bf, 0.1f);

    assert(unit.position.x < before.x - 1.0f);
    assert(unit.position.x != before.x || unit.position.y != before.y);
}

static void test_jam_relief_respects_lane_corridor_limit(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 2, 600.0f);
    unit.id = 201;  /* odd => prefer right */
    unit.position = (Vector2){ 770.0f, 1400.0f };
    unit.ticksSinceProgress = PATHFIND_JAM_RELIEF_TICKS;

    Entity target = make_test_entity(1, 1, 0.0f);
    target.position = (Vector2){ 770.0f, 1200.0f };
    target.ownerID = 1;
    unit.movementTargetId = target.id;

    Entity blockers[11];
    blockers[0] = make_test_entity(1, 1, 0.0f);
    blockers[0].position = (Vector2){ 770.0f, 1340.0f };              /* forward */
    blockers[1] = make_test_entity(1, 1, 0.0f);
    blockers[1].position = (Vector2){ 740.0f, 1348.0f };              /* left 30 */
    blockers[2] = make_test_entity(1, 1, 0.0f);
    blockers[2].position = (Vector2){ 800.0f, 1348.0f };              /* right 30 */
    blockers[3] = make_test_entity(1, 1, 0.0f);
    blockers[3].position = (Vector2){ 718.0f, 1370.0f };              /* left 60 */
    blockers[4] = make_test_entity(1, 1, 0.0f);
    blockers[4].position = (Vector2){ 822.0f, 1370.0f };              /* right 60 */
    blockers[5] = make_test_entity(1, 1, 0.0f);
    blockers[5].position = (Vector2){ 710.0f, 1400.0f };              /* left 90 */
    blockers[6] = make_test_entity(1, 1, 0.0f);
    blockers[6].position = (Vector2){ 718.0f, 1430.0f };              /* left 120 */
    blockers[7] = make_test_entity(1, 1, 0.0f);
    blockers[7].position = (Vector2){ 650.0f, 1400.0f };              /* left 180 */
    blockers[8] = make_test_entity(1, 1, 0.0f);
    blockers[8].position = (Vector2){ 666.0f, 1460.0f };              /* left 240 diag */
    blockers[9] = make_test_entity(1, 1, 0.0f);
    blockers[9].position = (Vector2){ 590.0f, 1400.0f };              /* left 270 */
    blockers[10] = make_test_entity(1, 1, 0.0f);
    blockers[10].position = (Vector2){ 614.0f, 1490.0f };             /* left 360 diag */

    bf_test_register(&bf, &unit);
    bf_test_register(&bf, &target);
    for (int i = 0; i < 11; i++) {
        bf_test_register(&bf, &blockers[i]);
    }

    Vector2 before = unit.position;
    pathfind_step_entity(&unit, &bf, 0.1f);

    assert(unit.position.x == before.x);
    assert(unit.position.y == before.y);
}

static void test_fully_boxed_in_unit_stays_put_after_jam_relief(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 2, 600.0f);
    unit.position = (Vector2){ 540.0f, 1400.0f };
    unit.ticksSinceProgress = PATHFIND_JAM_RELIEF_TICKS;

    Entity target = make_test_entity(1, 1, 0.0f);
    target.position = (Vector2){ 540.0f, 1200.0f };
    target.ownerID = 1;
    unit.movementTargetId = target.id;

    Entity blockers[17];
    blockers[0] = make_test_entity(1, 1, 0.0f);
    blockers[0].position = (Vector2){ 540.0f, 1340.0f };
    blockers[1] = make_test_entity(1, 1, 0.0f);
    blockers[1].position = (Vector2){ 510.0f, 1348.0f };
    blockers[2] = make_test_entity(1, 1, 0.0f);
    blockers[2].position = (Vector2){ 570.0f, 1348.0f };
    blockers[3] = make_test_entity(1, 1, 0.0f);
    blockers[3].position = (Vector2){ 488.0f, 1370.0f };
    blockers[4] = make_test_entity(1, 1, 0.0f);
    blockers[4].position = (Vector2){ 592.0f, 1370.0f };
    blockers[5] = make_test_entity(1, 1, 0.0f);
    blockers[5].position = (Vector2){ 480.0f, 1400.0f };
    blockers[6] = make_test_entity(1, 1, 0.0f);
    blockers[6].position = (Vector2){ 600.0f, 1400.0f };
    blockers[7] = make_test_entity(1, 1, 0.0f);
    blockers[7].position = (Vector2){ 488.0f, 1430.0f };
    blockers[8] = make_test_entity(1, 1, 0.0f);
    blockers[8].position = (Vector2){ 592.0f, 1430.0f };
    blockers[9] = make_test_entity(1, 1, 0.0f);
    blockers[9].position = (Vector2){ 420.0f, 1400.0f };
    blockers[10] = make_test_entity(1, 1, 0.0f);
    blockers[10].position = (Vector2){ 660.0f, 1400.0f };
    blockers[11] = make_test_entity(1, 1, 0.0f);
    blockers[11].position = (Vector2){ 436.0f, 1460.0f };
    blockers[12] = make_test_entity(1, 1, 0.0f);
    blockers[12].position = (Vector2){ 644.0f, 1460.0f };
    blockers[13] = make_test_entity(1, 1, 0.0f);
    blockers[13].position = (Vector2){ 360.0f, 1400.0f };
    blockers[14] = make_test_entity(1, 1, 0.0f);
    blockers[14].position = (Vector2){ 720.0f, 1400.0f };
    blockers[15] = make_test_entity(1, 1, 0.0f);
    blockers[15].position = (Vector2){ 384.0f, 1490.0f };
    blockers[16] = make_test_entity(1, 1, 0.0f);
    blockers[16].position = (Vector2){ 696.0f, 1490.0f };

    bf_test_register(&bf, &unit);
    bf_test_register(&bf, &target);
    for (int i = 0; i < 17; i++) {
        bf_test_register(&bf, &blockers[i]);
    }

    Vector2 before = unit.position;
    int beforeTicks = unit.ticksSinceProgress;
    pathfind_step_entity(&unit, &bf, 0.1f);

    assert(unit.position.x == before.x);
    assert(unit.position.y == before.y);
    assert(unit.ticksSinceProgress == beforeTicks + 1);
}

static void test_spawn_generated_same_lane_pack_makes_aggregate_progress(void) {
    Battlefield bf = make_test_battlefield();
    enum { PACK_SIZE = 24, BUILD_TICKS = 1800, DRAIN_TICKS = 1200 };
    Entity pack[PACK_SIZE];

    int spawned = test_spawn_same_lane_pack(&bf, pack, PACK_SIZE,
                                            SIDE_BOTTOM, 1, 1, BUILD_TICKS);
    assert(spawned == PACK_SIZE);

    float totalStartY = test_pack_total_y(pack, PACK_SIZE);
    test_step_pack(pack, PACK_SIZE, &bf, DRAIN_TICKS);
    float totalEndY = test_pack_total_y(pack, PACK_SIZE);
    int advancedUnits = test_pack_units_at_or_past_waypoint(pack, PACK_SIZE, 2);

    assert(totalEndY < totalStartY - 4500.0f);
    assert(advancedUnits >= 1);
}

static void test_spawn_generated_same_lane_pack_drains_forward_over_time(void) {
    Battlefield bf = make_test_battlefield();
    enum { PACK_SIZE = 24, BUILD_TICKS = 1800, WINDOW_TICKS = 120, WINDOW_COUNT = 5 };
    Entity pack[PACK_SIZE];

    int spawned = test_spawn_same_lane_pack(&bf, pack, PACK_SIZE,
                                            SIDE_BOTTOM, 1, 1, BUILD_TICKS);
    assert(spawned == PACK_SIZE);

    float previousTotalY = test_pack_total_y(pack, PACK_SIZE);
    for (int window = 0; window < WINDOW_COUNT; window++) {
        test_step_pack(pack, PACK_SIZE, &bf, WINDOW_TICKS);
        float currentTotalY = test_pack_total_y(pack, PACK_SIZE);
        assert(currentTotalY < previousTotalY - 30.0f);
        previousTotalY = currentTotalY;
    }
}

static void test_lane_end_with_pursuit_continues_walking(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, LANE_WAYPOINT_COUNT, 300.0f);
    unit.position = bf.laneWaypoints[SIDE_BOTTOM][1][LANE_WAYPOINT_COUNT - 1].v;

    Entity target = make_test_entity(1, 1, 0.0f);
    target.position = (Vector2){ unit.position.x + 120.0f, unit.position.y - 40.0f };
    target.ownerID = 1;

    unit.movementTargetId = target.id;

    bf_test_register(&bf, &unit);
    bf_test_register(&bf, &target);

    Vector2 before = unit.position;
    bool walking = pathfind_step_entity(&unit, &bf, 1.0f / 60.0f);

    assert(walking == true);
    assert(unit.state == ESTATE_WALKING);
    assert(unit.position.x != before.x || unit.position.y != before.y);
    assert(unit.movementTargetId == target.id);
}

static void test_lane_end_without_pursuit_idles_and_faces_enemy_base(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, LANE_WAYPOINT_COUNT, 300.0f);
    unit.position = bf.laneWaypoints[SIDE_BOTTOM][1][LANE_WAYPOINT_COUNT - 1].v;
    unit.movementTargetId = -1;

    bool walking = pathfind_step_entity(&unit, &bf, 1.0f / 60.0f);

    assert(walking == false);
    assert(unit.state == ESTATE_IDLE);
    assert(unit.presentationSide == SIDE_TOP);
    assert(unit.anim.dir == DIR_SIDE);
    assert(unit.anim.flipH == true);
    assert(approx_eq(unit.spriteRotationDegrees, 180.0f, 0.001f));
}

static void test_walk_facing_prefers_pursuit_goal_over_waypoint(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 2, 300.0f);
    unit.position = bf.laneWaypoints[SIDE_BOTTOM][1][1].v;

    Entity target = make_test_entity(1, 1, 0.0f);
    target.position = (Vector2){ unit.position.x + 120.0f, unit.position.y };
    target.ownerID = 1;

    unit.movementTargetId = target.id;
    bf_test_register(&bf, &target);

    pathfind_update_walk_facing(&unit, &bf);

    assert(unit.anim.dir == DIR_SIDE);
    assert(unit.anim.flipH == false);
}

static void test_body_radius_bounds_reject_edge_clipping_candidate(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 1, 300.0f);
    unit.position = (Vector2){ 30.0f, 30.0f };
    unit.bodyRadius = 30.0f;

    Vector2 before = unit.position;
    bool arrived = pathfind_move_toward_goal(&unit, (Vector2){ 0.0f, 0.0f }, 0.0f,
                                             &bf, 1.0f / 60.0f);

    assert(arrived == false);
    assert(unit.position.x == before.x);
    assert(unit.position.y == before.y);
    assert(unit.ticksSinceProgress == 1);
}

/* Sidestep: blocker sits slightly offset from the path so the follower can
 * route around it and reach the far waypoint. */
static void test_unit_sidesteps_around_offset_blocker(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 2, 300.0f);
    Vector2 wp1 = bf.laneWaypoints[SIDE_BOTTOM][1][1].v;
    Vector2 wp2 = bf.laneWaypoints[SIDE_BOTTOM][1][2].v;
    unit.position = wp1;

    /* Blocker offset laterally from the midpoint between wp1 and wp2 so
     * forward candidates overlap and sidesteps don't. */
    Entity blocker = make_test_entity(1, 1, 0.0f);
    blocker.position = (Vector2){
        (wp1.x + wp2.x) * 0.5f + 25.0f,
        (wp1.y + wp2.y) * 0.5f
    };
    blocker.bodyRadius = 14.0f;

    bf_test_register(&bf, &unit);
    bf_test_register(&bf, &blocker);

    for (int i = 0; i < 240; i++) {
        pathfind_step_entity(&unit, &bf, 1.0f / 60.0f);
    }

    /* At no point should the unit have overlapped the blocker. Verify now: */
    float bdx = unit.position.x - blocker.position.x;
    float bdy = unit.position.y - blocker.position.y;
    float bdist = sqrtf(bdx * bdx + bdy * bdy);
    float minDist = unit.bodyRadius + blocker.bodyRadius + PATHFIND_CONTACT_GAP;
    assert(bdist >= minDist - 0.001f);

    /* And it made meaningful forward progress past wp1 -- either advanced
     * waypoint or moved noticeably toward wp2. */
    bool advanced = unit.waypointIndex > 2;
    float currentToWp2 = sqrtf((unit.position.x - wp2.x) * (unit.position.x - wp2.x) +
                               (unit.position.y - wp2.y) * (unit.position.y - wp2.y));
    float wp1ToWp2 = sqrtf((wp1.x - wp2.x) * (wp1.x - wp2.x) +
                           (wp1.y - wp2.y) * (wp1.y - wp2.y));
    assert(advanced || currentToWp2 < wp1ToWp2 - 10.0f);
}

/* ---- Escape from existing overlap ---- */

/* A LANE entity spawned inside a large blocker's contact shell (e.g. a
 * knight spawning just in front of its own base after the base nav radius
 * grew in Phase 1) must be able to step outward. Pre-Phase-3 this case
 * deadlocked because every candidate was "overlapping" and therefore
 * illegal, even the forward step that strictly reduced overlap. */
static void test_escape_from_spawn_inside_contact_shell(void) {
    Battlefield bf = make_test_battlefield();

    /* Large stationary blocker -- mimic an inflated base nav shell. */
    Entity blocker = make_test_entity(1, 1, 0.0f);
    blocker.position = (Vector2){ 500.0f, 1650.0f };
    blocker.bodyRadius = 14.0f;
    blocker.navRadius = 56.0f;
    blocker.ownerID = 0;

    /* Knight spawned 32 px in front of the blocker center -- inside the
     * shell (14 + 56 + 2 = 72). Forward direction is -Y toward the goal. */
    Entity knight = make_test_entity(1, 1, 60.0f);
    knight.position = (Vector2){ 500.0f, 1618.0f };
    knight.bodyRadius = 14.0f;

    bf_test_register(&bf, &knight);
    bf_test_register(&bf, &blocker);

    /* Pre-check: knight overlaps blocker at spawn. */
    float dxBefore = knight.position.x - blocker.position.x;
    float dyBefore = knight.position.y - blocker.position.y;
    float distBefore = sqrtf(dxBefore * dxBefore + dyBefore * dyBefore);
    float shell = 14.0f + 56.0f + PATHFIND_CONTACT_GAP;
    assert(distBefore < shell);

    /* Run simulation. After enough ticks, knight must escape past the
     * contact shell -- 72 - 32 = 40 px to cover at step 1/frame, so
     * 240 frames is a generous upper bound. */
    Vector2 goal = { 500.0f, 200.0f };
    for (int i = 0; i < 240; i++) {
        pathfind_move_toward_goal(&knight, goal, 5.0f, &bf, 1.0f / 60.0f);
    }

    float dxAfter = knight.position.x - blocker.position.x;
    float dyAfter = knight.position.y - blocker.position.y;
    float distAfter = sqrtf(dxAfter * dxAfter + dyAfter * dyAfter);

    /* Knight must now be outside the contact shell, having escaped outward. */
    assert(distAfter >= shell - 0.001f);
}

/* Phase 2: free-mover steering (farmer navProfile = FREE_GOAL) */

/* Free mover with a blocker close enough to break every forward candidate
 * at normal step size still makes progress via the relaxed lateral tolerance
 * and jam relief. The unit must not move INTO a new overlap with the blocker. */
static void test_free_mover_sidesteps_close_blocker(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 1, 60.0f);
    unit.navProfile = NAV_PROFILE_FREE_GOAL;
    unit.position = (Vector2){ 500.0f, 500.0f };
    unit.bodyRadius = 14.0f;
    unit.ticksSinceProgress = PATHFIND_JAM_RELIEF_TICKS + 1;

    /* Blocker just at the edge of the contact shell (30 px = 14+14+2) so
     * the unit starts non-overlapping, but any forward step at dt=0.1
     * (step=6) would overlap. Pure side steps clear the shell. */
    Entity blocker = make_test_entity(1, 1, 0.0f);
    blocker.position = (Vector2){ 500.0f, 470.0f };
    blocker.bodyRadius = 14.0f;

    bf_test_register(&bf, &unit);
    bf_test_register(&bf, &blocker);

    Vector2 before = unit.position;
    Vector2 goal = { 500.0f, 200.0f };
    pathfind_move_toward_goal(&unit, goal, 5.0f, &bf, 0.1f);

    /* Free mover stepped sideways -- normal march picked the side candidate
     * under the relaxed lateral tolerance. */
    bool moved = (unit.position.x != before.x) || (unit.position.y != before.y);
    assert(moved);

    /* Post-step must be outside the contact shell (move must not enter
     * a fresh overlap). */
    float dxb = unit.position.x - blocker.position.x;
    float dyb = unit.position.y - blocker.position.y;
    float distb = sqrtf(dxb * dxb + dyb * dyb);
    float shell = unit.bodyRadius + blocker.bodyRadius + PATHFIND_CONTACT_GAP;
    assert(distb >= shell - 0.001f);
}

/* Regression: lane troops routed through pathfind_move_toward_goal (no jam
 * relief, no corridor enforcement) must still get the pre-Phase-2 strict
 * monotone-progress behavior. A LANE entity with a blocker squarely ahead
 * does not move -- exactly the body_radius_bounds_reject test's premise,
 * but demonstrated with a far goal so the step cap isn't the limiter. */
static void test_lane_mover_through_move_toward_goal_unchanged(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 1, 60.0f);
    unit.navProfile = NAV_PROFILE_LANE;
    unit.position = (Vector2){ 500.0f, 500.0f };
    unit.bodyRadius = 14.0f;
    unit.ticksSinceProgress = PATHFIND_JAM_RELIEF_TICKS + 1;

    Entity blocker = make_test_entity(1, 1, 0.0f);
    blocker.position = (Vector2){ 500.0f, 480.0f };
    blocker.bodyRadius = 14.0f;

    bf_test_register(&bf, &unit);
    bf_test_register(&bf, &blocker);

    Vector2 before = unit.position;
    Vector2 goal = { 500.0f, 200.0f };
    pathfind_move_toward_goal(&unit, goal, 5.0f, &bf, 0.1f);

    /* LANE profile through move_toward_goal: no jam relief (allowJamRelief
     * is false from the caller), no tangential tolerance. Unit stays put. */
    assert(unit.position.x == before.x);
    assert(unit.position.y == before.y);
}

/* Free mover near the board edge cannot phase off-board. The bounds check
 * uses nav radius (== body radius when navRadius is zero). */
static void test_free_mover_respects_board_bounds(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 1, 300.0f);
    unit.navProfile = NAV_PROFILE_FREE_GOAL;
    unit.position = (Vector2){ 30.0f, 30.0f };
    unit.bodyRadius = 30.0f;

    bf_test_register(&bf, &unit);

    Vector2 before = unit.position;
    pathfind_move_toward_goal(&unit, (Vector2){ 0.0f, 0.0f }, 0.0f,
                              &bf, 1.0f / 60.0f);

    /* Unit cannot move: forward of (0,0) would clip the -x/-y edges. The
     * relaxed tangential tolerance does not permit leaving the board. */
    assert(unit.position.x == before.x);
    assert(unit.position.y == before.y);
}

/* Free mover completes a trip past an offset blocker without stalling. The
 * blocker is placed so normal soft/hard candidates route around it; this
 * is the common case where slot-targeting alone would be enough. */
static void test_free_mover_reaches_goal_past_offset_blocker(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 1, 120.0f);
    unit.navProfile = NAV_PROFILE_FREE_GOAL;
    unit.position = (Vector2){ 500.0f, 700.0f };
    unit.bodyRadius = 14.0f;

    /* Blocker slightly off the straight line between unit and goal. */
    Entity blocker = make_test_entity(1, 1, 0.0f);
    blocker.position = (Vector2){ 515.0f, 620.0f };
    blocker.bodyRadius = 14.0f;

    bf_test_register(&bf, &unit);
    bf_test_register(&bf, &blocker);

    Vector2 goal = { 500.0f, 500.0f };
    bool arrived = false;
    for (int i = 0; i < 400; i++) {
        arrived = pathfind_move_toward_goal(&unit, goal, 6.0f, &bf, 0.1f);
        if (arrived) break;

        /* Never allowed to overlap the blocker mid-traversal. */
        float dxb = unit.position.x - blocker.position.x;
        float dyb = unit.position.y - blocker.position.y;
        float distb = sqrtf(dxb * dxb + dyb * dyb);
        float shell = unit.bodyRadius + blocker.bodyRadius + PATHFIND_CONTACT_GAP;
        assert(distb >= shell - 0.001f);
    }

    assert(arrived);
}

static void test_assault_soft_overlap_is_capped_for_moving_allies(void) {
    Battlefield bf = make_test_battlefield();

    Entity unit = make_test_entity(1, 2, 60.0f);
    unit.navProfile = NAV_PROFILE_ASSAULT;
    unit.position = (Vector2){ 500.0f, 500.0f };
    unit.bodyRadius = 14.0f;

    Entity ally = make_test_entity(1, 2, 60.0f);
    ally.navProfile = NAV_PROFILE_ASSAULT;
    ally.position = (Vector2){ 500.0f, 469.0f };
    ally.bodyRadius = 14.0f;

    Entity target = make_test_entity(1, 1, 0.0f);
    target.id = 999;
    target.position = (Vector2){ 500.0f, 220.0f };
    target.ownerID = 1;

    unit.movementTargetId = target.id;
    ally.movementTargetId = target.id;

    bf_test_register(&bf, &unit);
    bf_test_register(&bf, &ally);
    bf_test_register(&bf, &target);

    Vector2 before = unit.position;
    bool walking = pathfind_step_entity(&unit, &bf, 0.1f);

    assert(walking == true);
    assert(unit.position.y < before.y);

    float dx = unit.position.x - ally.position.x;
    float dy = unit.position.y - ally.position.y;
    float dist = sqrtf(dx * dx + dy * dy);
    float shell = unit.bodyRadius + ally.bodyRadius + PATHFIND_CONTACT_GAP;
    float baseAllowance = fminf(PATHFIND_ALLY_SOFT_OVERLAP_MAX,
                                (unit.bodyRadius + ally.bodyRadius) *
                                PATHFIND_ALLY_SOFT_OVERLAP_RATIO);
    float allowance = fminf(PATHFIND_ASSAULT_SAME_TARGET_SOFT_OVERLAP_MAX,
                            fminf(PATHFIND_ASSAULT_ALLY_SOFT_OVERLAP_MAX,
                                  (unit.bodyRadius + ally.bodyRadius) *
                                  PATHFIND_ASSAULT_ALLY_SOFT_OVERLAP_RATIO) +
                            PATHFIND_ASSAULT_SAME_TARGET_SOFT_OVERLAP_BONUS);

    assert(dist < shell);
    assert(dist < shell - baseAllowance - 0.1f);
    assert(dist >= shell - allowance - 0.001f);
}

static void test_assault_target_allows_entry_inside_static_nav_shell(void) {
    Battlefield bf = make_test_battlefield();

    Entity attacker = make_test_entity(1, 2, 120.0f);
    attacker.navProfile = NAV_PROFILE_ASSAULT;
    attacker.position = (Vector2){ 540.0f, 1500.0f };
    attacker.bodyRadius = 14.0f;

    Entity base = make_test_entity(1, 1, 0.0f);
    base.id = 777;
    base.type = ENTITY_BUILDING;
    base.navProfile = NAV_PROFILE_STATIC;
    base.position = (Vector2){ 540.0f, 1616.0f };
    base.bodyRadius = 16.0f;
    base.navRadius = 56.0f;
    base.ownerID = 1;

    attacker.movementTargetId = base.id;

    bf_test_register(&bf, &attacker);
    bf_test_register(&bf, &base);

    for (int i = 0; i < 180; i++) {
        pathfind_step_entity(&attacker, &bf, 1.0f / 60.0f);
    }

    float dx = attacker.position.x - base.position.x;
    float dy = attacker.position.y - base.position.y;
    float dist = sqrtf(dx * dx + dy * dy);
    float navShell = attacker.bodyRadius + base.navRadius + PATHFIND_CONTACT_GAP;
    float blockerShell = attacker.bodyRadius +
                         combat_target_contact_radius(&base) +
                         PATHFIND_CONTACT_GAP;

    assert(dist < navShell - 1.0f);
    assert(dist >= blockerShell - 2.0f);
}

static void test_same_target_assault_contact_cloud_allows_overlap(void) {
    Battlefield bf = make_test_battlefield();

    Entity attacker = make_test_entity(1, 2, 200.0f);
    attacker.navProfile = NAV_PROFILE_ASSAULT;
    attacker.position = (Vector2){ 540.0f, 1538.0f };
    attacker.bodyRadius = 14.0f;

    Entity ally = make_test_entity(1, 2, 0.0f);
    ally.navProfile = NAV_PROFILE_ASSAULT;
    ally.position = (Vector2){ 540.0f, 1568.0f };
    ally.bodyRadius = 14.0f;

    Entity base = make_test_entity(1, 1, 0.0f);
    base.id = 888;
    base.type = ENTITY_BUILDING;
    base.navProfile = NAV_PROFILE_STATIC;
    base.position = (Vector2){ 540.0f, 1616.0f };
    base.bodyRadius = 16.0f;
    base.navRadius = BASE_NAV_RADIUS;
    base.ownerID = 1;

    attacker.movementTargetId = base.id;
    ally.movementTargetId = base.id;

    bf_test_register(&bf, &attacker);
    bf_test_register(&bf, &ally);
    bf_test_register(&bf, &base);

    pathfind_move_toward_goal(&attacker, base.position,
                              combat_target_contact_radius(&base) +
                              attacker.bodyRadius +
                              PATHFIND_CONTACT_GAP +
                              combat_melee_reach_distance(&attacker, &base),
                              &bf, 0.1f);

    float dx = attacker.position.x - ally.position.x;
    float dy = attacker.position.y - ally.position.y;
    float dist = sqrtf(dx * dx + dy * dy);
    float shell = attacker.bodyRadius + ally.bodyRadius + PATHFIND_CONTACT_GAP;

    assert(attacker.position.y > 1550.0f);
    assert(dist < shell - 1.0f);
}

static void test_late_arriving_attacker_overlaps_packed_front_blob(void) {
    Battlefield bf = make_test_battlefield();

    Entity late = make_test_entity(1, 2, 120.0f);
    late.navProfile = NAV_PROFILE_ASSAULT;
    late.position = (Vector2){ 540.0f, 1548.0f };
    late.bodyRadius = 14.0f;

    Entity allyA = make_test_entity(1, 2, 0.0f);
    allyA.navProfile = NAV_PROFILE_ASSAULT;
    allyA.position = (Vector2){ 540.0f, 1568.0f };
    allyA.bodyRadius = 14.0f;

    Entity allyB = make_test_entity(1, 2, 0.0f);
    allyB.navProfile = NAV_PROFILE_ASSAULT;
    allyB.position = (Vector2){ 522.0f, 1576.0f };
    allyB.bodyRadius = 14.0f;

    Entity allyC = make_test_entity(1, 2, 0.0f);
    allyC.navProfile = NAV_PROFILE_ASSAULT;
    allyC.position = (Vector2){ 558.0f, 1576.0f };
    allyC.bodyRadius = 14.0f;

    Entity base = make_test_entity(1, 1, 0.0f);
    base.id = 889;
    base.type = ENTITY_BUILDING;
    base.navProfile = NAV_PROFILE_STATIC;
    base.position = (Vector2){ 540.0f, 1616.0f };
    base.bodyRadius = 16.0f;
    base.navRadius = BASE_NAV_RADIUS;
    base.ownerID = 1;

    late.movementTargetId = base.id;
    allyA.movementTargetId = base.id;
    allyB.movementTargetId = base.id;
    allyC.movementTargetId = base.id;

    bf_test_register(&bf, &late);
    bf_test_register(&bf, &allyA);
    bf_test_register(&bf, &allyB);
    bf_test_register(&bf, &allyC);
    bf_test_register(&bf, &base);

    for (int tick = 0; tick < 24; tick++) {
        pathfind_step_entity(&late, &bf, 1.0f / 60.0f);
    }

    float attackRadius = combat_static_target_attack_radius(&late, &base);
    float lateDx = late.position.x - base.position.x;
    float lateDy = late.position.y - base.position.y;
    float lateDist = sqrtf(lateDx * lateDx + lateDy * lateDy);
    float overlapDistA = sqrtf((late.position.x - allyA.position.x) * (late.position.x - allyA.position.x) +
                               (late.position.y - allyA.position.y) * (late.position.y - allyA.position.y));
    float shell = late.bodyRadius + allyA.bodyRadius + PATHFIND_CONTACT_GAP;

    assert(fabsf(late.position.x - 540.0f) <= 8.0f);
    assert(lateDist <= attackRadius + 0.5f);
    assert(overlapDistA < shell - 1.0f);
}

static void test_assault_contact_cloud_allows_entry_through_front_line(void) {
    Battlefield bf = make_test_battlefield();

    Entity late = make_test_entity(1, 2, 120.0f);
    late.navProfile = NAV_PROFILE_ASSAULT;
    late.position = (Vector2){ 540.0f, 1532.0f };
    late.bodyRadius = 14.0f;

    Entity ally = make_test_entity(1, 2, 0.0f);
    ally.navProfile = NAV_PROFILE_ASSAULT;
    ally.position = (Vector2){ 540.0f, 1566.0f };
    ally.bodyRadius = 14.0f;

    Entity base = make_test_entity(1, 1, 0.0f);
    base.id = 890;
    base.type = ENTITY_BUILDING;
    base.navProfile = NAV_PROFILE_STATIC;
    base.position = (Vector2){ 540.0f, 1616.0f };
    base.bodyRadius = 16.0f;
    base.navRadius = BASE_NAV_RADIUS;
    base.ownerID = 1;

    late.movementTargetId = base.id;
    ally.movementTargetId = base.id;

    bf_test_register(&bf, &late);
    bf_test_register(&bf, &ally);
    bf_test_register(&bf, &base);

    float attackRadius = combat_static_target_attack_radius(&late, &base);
    pathfind_move_toward_goal(&late, base.position, attackRadius, &bf, 0.15f);

    float overlapDist = sqrtf((late.position.x - ally.position.x) * (late.position.x - ally.position.x) +
                              (late.position.y - ally.position.y) * (late.position.y - ally.position.y));
    float shell = late.bodyRadius + ally.bodyRadius + PATHFIND_CONTACT_GAP;

    assert(fabsf(late.position.x - 540.0f) <= 6.0f);
    assert(late.position.y >= 1548.0f);
    assert(overlapDist < shell - PATHFIND_ASSAULT_SAME_TARGET_SOFT_OVERLAP_MAX - 1.0f);
}

static void test_same_lane_assault_blob_spreads_subtly_near_base(void) {
    Battlefield bf = make_test_battlefield();

    Entity base = make_test_entity(1, 1, 0.0f);
    base.id = 891;
    base.type = ENTITY_BUILDING;
    base.navProfile = NAV_PROFILE_STATIC;
    base.position = (Vector2){ 540.0f, 1616.0f };
    base.bodyRadius = 16.0f;
    base.navRadius = BASE_NAV_RADIUS;
    base.ownerID = 1;

    enum { ATTACKER_COUNT = 8 };
    Entity attackers[ATTACKER_COUNT];
    for (int i = 0; i < ATTACKER_COUNT; i++) {
        attackers[i] = make_test_entity(1, 2, 120.0f);
        attackers[i].navProfile = NAV_PROFILE_ASSAULT;
        attackers[i].position = (Vector2){ 540.0f, 1456.0f + (float)i * 18.0f };
        attackers[i].bodyRadius = 14.0f;
        attackers[i].movementTargetId = base.id;
    }

    bf_test_register(&bf, &base);
    for (int i = 0; i < ATTACKER_COUNT; i++) {
        bf_test_register(&bf, &attackers[i]);
    }

    for (int tick = 0; tick < 360; tick++) {
        for (int i = 0; i < ATTACKER_COUNT; i++) {
            pathfind_step_entity(&attackers[i], &bf, 1.0f / 60.0f);
        }
    }

    float minX = attackers[0].position.x;
    float maxX = attackers[0].position.x;
    bool sawLeft = false;
    bool sawRight = false;
    for (int i = 0; i < ATTACKER_COUNT; i++) {
        float dx = attackers[i].position.x - base.position.x;
        float dy = attackers[i].position.y - base.position.y;
        float dist = sqrtf(dx * dx + dy * dy);
        float attackRadius = combat_static_target_attack_radius(&attackers[i], &base);

        if (attackers[i].position.x < minX) minX = attackers[i].position.x;
        if (attackers[i].position.x > maxX) maxX = attackers[i].position.x;
        if (attackers[i].position.x < base.position.x - 4.0f) sawLeft = true;
        if (attackers[i].position.x > base.position.x + 4.0f) sawRight = true;
        assert(dist <= attackRadius + 1.0f);
    }

    float spread = maxX - minX;
    assert(sawLeft);
    assert(sawRight);
    assert(spread >= 12.0f);
    assert(spread <= 72.0f);
}

static void test_many_attackers_converge_on_static_target_without_slot_cap(void) {
    Battlefield bf = make_test_battlefield();

    Entity base = make_test_entity(1, 1, 0.0f);
    base.id = 990;
    base.type = ENTITY_BUILDING;
    base.navProfile = NAV_PROFILE_STATIC;
    base.position = (Vector2){ 540.0f, 1616.0f };
    base.bodyRadius = 16.0f;
    base.navRadius = BASE_NAV_RADIUS;
    base.ownerID = 1;

    enum { ATTACKER_COUNT = 16 };
    Entity attackers[ATTACKER_COUNT];
    for (int i = 0; i < ATTACKER_COUNT; i++) {
        attackers[i] = make_test_entity(1, 2, (i < 12) ? 120.0f : 105.0f);
        attackers[i].navProfile = NAV_PROFILE_ASSAULT;
        attackers[i].position = (Vector2){
            486.0f + (float)(i % 4) * 36.0f,
            1458.0f + (float)(i / 4) * 28.0f
        };
        attackers[i].bodyRadius = (i < 12) ? 14.0f : 18.0f;
        attackers[i].attackRange = 50.0f;
        attackers[i].movementTargetId = base.id;
    }

    bf_test_register(&bf, &base);
    for (int i = 0; i < ATTACKER_COUNT; i++) {
        bf_test_register(&bf, &attackers[i]);
    }

    for (int tick = 0; tick < 480; tick++) {
        for (int i = 0; i < ATTACKER_COUNT; i++) {
            pathfind_step_entity(&attackers[i], &bf, 1.0f / 60.0f);
        }
    }

    for (int i = 0; i < ATTACKER_COUNT; i++) {
        float dx = attackers[i].position.x - base.position.x;
        float dy = attackers[i].position.y - base.position.y;
        float dist = sqrtf(dx * dx + dy * dy);
        float attackRadius = combat_static_target_attack_radius(&attackers[i], &base);
        float occupancyRadius = combat_static_target_occupancy_radius(&attackers[i], &base);
        float blockerShell = attackers[i].bodyRadius +
                             combat_target_contact_radius(&base) +
                             PATHFIND_CONTACT_GAP;

        assert(dist <= occupancyRadius + 1.0f);
        assert(dist <= attackRadius + 1.0f);
        assert(dist >= blockerShell - 1.0f);
    }
}

static void test_primary_deposit_contact_cloud_allows_overlap(void) {
    Battlefield bf = make_test_battlefield();

    Entity farmer = make_test_entity(-1, -1, 200.0f);
    farmer.navProfile = NAV_PROFILE_FREE_GOAL;
    farmer.position = (Vector2){ 540.0f, 1520.0f };
    farmer.bodyRadius = 14.0f;

    Entity ally = make_test_entity(-1, -1, 0.0f);
    ally.navProfile = NAV_PROFILE_FREE_GOAL;
    ally.position = (Vector2){ 540.0f, 1550.0f };
    ally.bodyRadius = 14.0f;

    Entity base = make_test_entity(1, 1, 0.0f);
    base.id = 889;
    base.type = ENTITY_BUILDING;
    base.navProfile = NAV_PROFILE_STATIC;
    base.position = (Vector2){ 540.0f, 1616.0f };
    base.bodyRadius = 16.0f;
    base.navRadius = BASE_NAV_RADIUS;

    farmer.movementTargetId = base.id;
    farmer.reservedDepositSlotKind = DEPOSIT_SLOT_PRIMARY;
    ally.movementTargetId = base.id;
    ally.reservedDepositSlotKind = DEPOSIT_SLOT_PRIMARY;

    bf_test_register(&bf, &farmer);
    bf_test_register(&bf, &ally);
    bf_test_register(&bf, &base);

    pathfind_move_toward_goal(&farmer, base.position,
                              base.navRadius + farmer.bodyRadius + BASE_DEPOSIT_SLOT_GAP,
                              &bf, 0.1f);

    float dx = farmer.position.x - ally.position.x;
    float dy = farmer.position.y - ally.position.y;
    float dist = sqrtf(dx * dx + dy * dy);
    float shell = farmer.bodyRadius + ally.bodyRadius + PATHFIND_CONTACT_GAP;

    assert(farmer.position.y > 1535.0f);
    assert(dist < shell - 1.0f);
}

/* ---- CORE-01 bonus: Invalid lane produces IDLE ---- */
static void test_invalid_lane_idles(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(-1, 1, 100.0f);
    e.position = (Vector2){500, 1500};

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == false);
    assert(e.state == ESTATE_IDLE);

    Entity e2 = make_test_entity(3, 1, 100.0f);
    e2.position = (Vector2){500, 1500};
    walking = pathfind_step_entity(&e2, &bf, 1.0f / 60.0f);
    assert(walking == false);
    assert(e2.state == ESTATE_IDLE);
}

/* ---- main ---- */
int main(void) {
    printf("Running pathfinding tests...\n");
    test_canonical_waypoints_progress();         printf("  PASS: test_canonical_waypoints_progress\n");
    test_center_lane_consistent_x();             printf("  PASS: test_center_lane_consistent_x\n");
    test_movement_step_advances_waypoint();       printf("  PASS: test_movement_step_advances_waypoint\n");
    test_idle_at_last_waypoint();                 printf("  PASS: test_idle_at_last_waypoint\n");
    test_sprite_direction();                      printf("  PASS: test_sprite_direction\n");
    test_sprite_direction_for_side();             printf("  PASS: test_sprite_direction_for_side\n");
    test_presentation_side_for_position();        printf("  PASS: test_presentation_side_for_position\n");
    test_sprite_rotation_for_side();              printf("  PASS: test_sprite_rotation_for_side\n");
    test_seam_overlap_preserves_presentation_bottom_to_top();
    printf("  PASS: test_seam_overlap_preserves_presentation_bottom_to_top\n");
    test_seam_clear_defers_presentation_bottom_to_top();
    printf("  PASS: test_seam_clear_defers_presentation_bottom_to_top\n");
    test_walk_loop_commit_swaps_presentation_bottom_to_top();
    printf("  PASS: test_walk_loop_commit_swaps_presentation_bottom_to_top\n");
    test_seam_overlap_preserves_presentation_top_to_bottom();
    printf("  PASS: test_seam_overlap_preserves_presentation_top_to_bottom\n");
    test_seam_clear_defers_presentation_top_to_bottom();
    printf("  PASS: test_seam_clear_defers_presentation_top_to_bottom\n");
    test_walk_loop_commit_swaps_presentation_top_to_bottom();
    printf("  PASS: test_walk_loop_commit_swaps_presentation_top_to_bottom\n");
    test_invalid_lane_idles();                    printf("  PASS: test_invalid_lane_idles\n");

    test_clear_lane_forward_still_advances();     printf("  PASS: test_clear_lane_forward_still_advances\n");
    test_lane_progress_projection_is_monotonic_off_centerline();
    printf("  PASS: test_lane_progress_projection_is_monotonic_off_centerline\n");
    test_lane_progress_prevents_backtracking_to_stale_waypoint();
    printf("  PASS: test_lane_progress_prevents_backtracking_to_stale_waypoint\n");
    test_blocker_on_waypoint_stays_queued_without_burning_waypoints();
    printf("  PASS: test_blocker_on_waypoint_stays_queued_without_burning_waypoints\n");
    test_all_candidates_blocked_stays_put();      printf("  PASS: test_all_candidates_blocked_stays_put\n");
    test_last_waypoint_no_jitter();               printf("  PASS: test_last_waypoint_no_jitter\n");
    test_engagement_goal_stops_at_contact_distance();
    printf("  PASS: test_engagement_goal_stops_at_contact_distance\n");
    test_jam_relief_shuffles_after_threshold();
    printf("  PASS: test_jam_relief_shuffles_after_threshold\n");
    test_jam_relief_respects_lane_corridor_limit();
    printf("  PASS: test_jam_relief_respects_lane_corridor_limit\n");
    test_fully_boxed_in_unit_stays_put_after_jam_relief();
    printf("  PASS: test_fully_boxed_in_unit_stays_put_after_jam_relief\n");
    test_spawn_generated_same_lane_pack_makes_aggregate_progress();
    printf("  PASS: test_spawn_generated_same_lane_pack_makes_aggregate_progress\n");
    test_spawn_generated_same_lane_pack_drains_forward_over_time();
    printf("  PASS: test_spawn_generated_same_lane_pack_drains_forward_over_time\n");
    test_lane_end_with_pursuit_continues_walking();
    printf("  PASS: test_lane_end_with_pursuit_continues_walking\n");
    test_lane_end_without_pursuit_idles_and_faces_enemy_base();
    printf("  PASS: test_lane_end_without_pursuit_idles_and_faces_enemy_base\n");
    test_walk_facing_prefers_pursuit_goal_over_waypoint();
    printf("  PASS: test_walk_facing_prefers_pursuit_goal_over_waypoint\n");
    test_body_radius_bounds_reject_edge_clipping_candidate();
    printf("  PASS: test_body_radius_bounds_reject_edge_clipping_candidate\n");
    test_unit_sidesteps_around_offset_blocker();  printf("  PASS: test_unit_sidesteps_around_offset_blocker\n");
    test_escape_from_spawn_inside_contact_shell();
    printf("  PASS: test_escape_from_spawn_inside_contact_shell\n");
    test_free_mover_sidesteps_close_blocker();
    printf("  PASS: test_free_mover_sidesteps_close_blocker\n");
    test_lane_mover_through_move_toward_goal_unchanged();
    printf("  PASS: test_lane_mover_through_move_toward_goal_unchanged\n");
    test_free_mover_respects_board_bounds();
    printf("  PASS: test_free_mover_respects_board_bounds\n");
    test_free_mover_reaches_goal_past_offset_blocker();
    printf("  PASS: test_free_mover_reaches_goal_past_offset_blocker\n");
    test_assault_soft_overlap_is_capped_for_moving_allies();
    printf("  PASS: test_assault_soft_overlap_is_capped_for_moving_allies\n");
    test_assault_target_allows_entry_inside_static_nav_shell();
    printf("  PASS: test_assault_target_allows_entry_inside_static_nav_shell\n");
    test_same_target_assault_contact_cloud_allows_overlap();
    printf("  PASS: test_same_target_assault_contact_cloud_allows_overlap\n");
    test_late_arriving_attacker_overlaps_packed_front_blob();
    printf("  PASS: test_late_arriving_attacker_overlaps_packed_front_blob\n");
    test_assault_contact_cloud_allows_entry_through_front_line();
    printf("  PASS: test_assault_contact_cloud_allows_entry_through_front_line\n");
    test_same_lane_assault_blob_spreads_subtly_near_base();
    printf("  PASS: test_same_lane_assault_blob_spreads_subtly_near_base\n");
    test_many_attackers_converge_on_static_target_without_slot_cap();
    printf("  PASS: test_many_attackers_converge_on_static_target_without_slot_cap\n");
    test_primary_deposit_contact_cloud_allows_overlap();
    printf("  PASS: test_primary_deposit_contact_cloud_allows_overlap\n");

    printf("\nAll 45 tests passed!\n");
    return 0;
}
