/*
 * Unit tests for src/logic/pathfinding.c
 *
 * Self-contained: redefines minimal type stubs and includes pathfinding.c
 * directly to avoid the heavy types.h include chain (Raylib, sqlite3, biome).
 * Compiles with `make test` using only -lm.
 *
 * Updated for Plan 11-05: lane_generate_waypoints deleted (canonical waypoints
 * are generated by bf_init in battlefield.c). The Player struct stub is minimal.
 * Tests focus on pathfind_step_entity and direction helpers using the
 * Battlefield canonical waypoint interface.
 */

#include <assert.h>
#include <stdio.h>
#include <math.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>

/* ---- Prevent pathfinding.c's includes from pulling in heavy headers ---- */
#define NFC_CARDGAME_TYPES_H
#define NFC_CARDGAME_PATHFINDING_H
#define NFC_CARDGAME_PLAYER_H
#define NFC_CARDGAME_ENTITIES_H
#define NFC_CARDGAME_BATTLEFIELD_H
#define NFC_CARDGAME_BATTLEFIELD_MATH_H

/* ---- Config defines (must match src/core/config.h) ---- */
#define LANE_WAYPOINT_COUNT  8
#define LANE_BOW_INTENSITY   0.3f
#define LANE_JITTER_RADIUS   10.0f
#define PI_F 3.14159265f
#define NUM_CARD_SLOTS 3
#define MAX_ENTITIES 64
#define BOARD_WIDTH  1080
#define BOARD_HEIGHT 1920
#define SEAM_Y       960

/* ---- Minimal type stubs ---- */
typedef struct { float x; float y; } Vector2;
typedef struct { float x; float y; float width; float height; } Rectangle;

typedef enum { ANIM_IDLE, ANIM_RUN, ANIM_WALK, ANIM_HURT, ANIM_DEATH, ANIM_ATTACK, ANIM_COUNT } AnimationType;
typedef enum { DIR_SIDE, DIR_DOWN, DIR_UP, DIR_COUNT } SpriteDirection;
typedef enum { ESTATE_IDLE, ESTATE_WALKING, ESTATE_ATTACKING, ESTATE_DEAD } EntityState;
typedef enum { TARGET_NEAREST, TARGET_BUILDING, TARGET_SPECIFIC_TYPE } TargetingMode;
typedef enum { ENTITY_TROOP, ENTITY_BUILDING, ENTITY_PROJECTILE } EntityType;
typedef enum { FACTION_PLAYER1, FACTION_PLAYER2 } Faction;
typedef enum { SIDE_BOTTOM, SIDE_TOP } BattleSide;

typedef struct {
    AnimationType anim;
    SpriteDirection dir;
    float elapsed;
    float cycleDuration;
    float normalizedTime;
    bool oneShot;
    bool finished;
    bool flipH;
} AnimState;

typedef struct {
    float prevNormalized;
    float currNormalized;
    bool finishedThisTick;
    bool loopedThisTick;
} AnimPlaybackEvent;

typedef struct { void *texture; int frameWidth; int frameHeight; int frameCount; void *visibleBounds; } SpriteSheet;
typedef struct { SpriteSheet anims[ANIM_COUNT]; } CharacterSprite;

typedef struct Entity Entity;

struct Entity {
    int id;
    EntityType type;
    Faction faction;
    EntityState state;
    Vector2 position;
    float moveSpeed;
    int hp, maxHP;
    int attack;
    float attackSpeed;
    float attackRange;
    float attackCooldown;
    int attackTargetId;
    TargetingMode targeting;
    const char *targetType;
    AnimState anim;
    const CharacterSprite *sprite;
    int spriteType; // SpriteType enum, but int to avoid pulling in sprite_renderer.h
    float spriteScale;
    float spriteRotationDegrees;
    BattleSide presentationSide;
    int ownerID;
    int lane;
    int waypointIndex;
    float hitFlashTimer;
    bool alive;
    bool markedForRemoval;
};

/* ---- Battlefield stub (minimal for pathfinding) ---- */
typedef struct { Vector2 v; } CanonicalPos;
typedef struct { Vector2 v; BattleSide side; } SideLocalPos;

#define BF_ASSERT_IN_BOUNDS(pos, w, h) \
    assert((pos).v.x >= 0.0f && (pos).v.x <= (w) && \
           (pos).v.y >= 0.0f && (pos).v.y <= (h) && \
           "Entity position outside canonical board bounds")

typedef struct Battlefield {
    float boardWidth;
    float boardHeight;
    float seamY;
    /* Canonical lane waypoints: [side][lane][waypointIdx] */
    CanonicalPos laneWaypoints[2][3][LANE_WAYPOINT_COUNT];
    /* Slot spawn anchors: [side][slot] */
    CanonicalPos slotSpawnAnchors[2][NUM_CARD_SLOTS];
} Battlefield;

/* ---- Stub functions for battlefield API used by pathfinding.c ---- */
BattleSide bf_side_for_player(int playerID) {
    return (playerID == 0) ? SIDE_BOTTOM : SIDE_TOP;
}

CanonicalPos bf_waypoint(const Battlefield *bf, BattleSide side, int lane, int waypointIdx) {
    if (lane < 0 || lane >= 3 || waypointIdx < 0 || waypointIdx >= LANE_WAYPOINT_COUNT) {
        CanonicalPos fallback = { .v = { bf->boardWidth / 2.0f, bf->boardHeight / 2.0f } };
        return fallback;
    }
    return bf->laneWaypoints[side][lane][waypointIdx];
}

CanonicalPos bf_base_anchor(const Battlefield *bf, BattleSide side) {
    CanonicalPos base = { .v = { bf->boardWidth * 0.5f, (side == SIDE_TOP) ? 64.0f : (bf->boardHeight - 64.0f) } };
    return base;
}

BattleSide bf_side_for_pos(CanonicalPos pos, float seamY) {
    return (pos.v.y < seamY) ? SIDE_TOP : SIDE_BOTTOM;
}

bool bf_crosses_seam(CanonicalPos pos, float spriteHeight, float seamY) {
    float halfH = spriteHeight * 0.5f;
    return (pos.v.y - halfH < seamY) && (pos.v.y + halfH > seamY);
}

const SpriteSheet *sprite_sheet_get(const CharacterSprite *cs, AnimationType anim) {
    if (!cs || anim < 0 || anim >= ANIM_COUNT) return NULL;
    return &cs->anims[anim];
}

/* ---- Stubs for functions pathfinding.c calls ---- */

void entity_set_state(Entity *e, EntityState newState) {
    if (e) e->state = newState;
}

/* ---- Forward declarations for functions in pathfinding.c ---- */
bool pathfind_step_entity(Entity *e, const Battlefield *bf, float deltaTime);
void pathfind_apply_direction(AnimState *anim, Vector2 diff);
BattleSide pathfind_presentation_side_for_position(Vector2 position, float seamY);
void pathfind_sync_presentation(Entity *e, const Battlefield *bf);
void pathfind_commit_presentation(Entity *e, const Battlefield *bf);
void pathfind_update_walk_facing(Entity *e, const Battlefield *bf);
void pathfind_apply_direction_for_side(AnimState *anim, Vector2 diff, BattleSide side);
float pathfind_sprite_rotation_for_side(SpriteDirection dir, BattleSide side);

/* ---- Include production code under test ---- */
#include "../src/logic/pathfinding.c"

/* ---- Test helpers ---- */

static bool approx_eq(float a, float b, float eps) {
    return fabsf(a - b) < eps;
}

/* Build a Battlefield stub with manually generated straight-line waypoints for
 * both sides. This provides predictable positions for testing pathfinding
 * behavior without depending on bf_init's full logic. */
static Battlefield make_test_battlefield(void) {
    Battlefield bf;
    memset(&bf, 0, sizeof(Battlefield));
    bf.boardWidth = BOARD_WIDTH;
    bf.boardHeight = BOARD_HEIGHT;
    bf.seamY = SEAM_Y;

    float laneWidth = (float)BOARD_WIDTH / 3.0f;
    float bottomSpawnY = 960.0f + 960.0f * 0.8f; /* 1728 */
    float bottomEndY = 192.0f;
    float topSpawnY = 192.0f;
    float topEndY = 960.0f + 960.0f * 0.8f; /* 1728 */

    for (int lane = 0; lane < 3; lane++) {
        float centerX = (lane + 0.5f) * laneWidth;
        for (int wp = 0; wp < LANE_WAYPOINT_COUNT; wp++) {
            float t = (float)wp / (float)(LANE_WAYPOINT_COUNT - 1);
            float bottomY = bottomSpawnY + (bottomEndY - bottomSpawnY) * t;
            float topY = topSpawnY + (topEndY - topSpawnY) * t;
            bf.laneWaypoints[SIDE_BOTTOM][lane][wp].v = (Vector2){ centerX, bottomY };
            bf.laneWaypoints[SIDE_TOP][lane][wp].v = (Vector2){ centerX, topY };
        }
        bf.slotSpawnAnchors[SIDE_BOTTOM][lane] = bf.laneWaypoints[SIDE_BOTTOM][lane][0];
        bf.slotSpawnAnchors[SIDE_TOP][lane] = bf.laneWaypoints[SIDE_TOP][lane][0];
    }

    return bf;
}

static Entity make_test_entity(int lane, int waypointIndex, float moveSpeed) {
    static CharacterSprite testSprite = {
        .anims = {
            [ANIM_IDLE] = { .frameHeight = 64 },
            [ANIM_RUN] = { .frameHeight = 64 },
            [ANIM_WALK] = { .frameHeight = 64 },
            [ANIM_HURT] = { .frameHeight = 64 },
            [ANIM_DEATH] = { .frameHeight = 64 },
            [ANIM_ATTACK] = { .frameHeight = 64 },
        }
    };
    Entity e;
    memset(&e, 0, sizeof(Entity));
    e.lane = lane;
    e.waypointIndex = waypointIndex;
    e.moveSpeed = moveSpeed;
    e.state = ESTATE_WALKING;
    e.anim.anim = ANIM_WALK;
    e.anim.dir = DIR_UP;
    e.anim.flipH = false;
    e.sprite = &testSprite;
    e.spriteScale = 1.0f;
    e.presentationSide = SIDE_BOTTOM;
    e.alive = true;
    e.ownerID = 0;  // SIDE_BOTTOM
    return e;
}

/* ---- CORE-01: Canonical waypoints progress toward enemy ---- */
static void test_canonical_waypoints_progress(void) {
    Battlefield bf = make_test_battlefield();

    for (int lane = 0; lane < 3; lane++) {
        /* Waypoints progress toward enemy (Y decreases for SIDE_BOTTOM) */
        for (int i = 1; i < LANE_WAYPOINT_COUNT; i++) {
            assert(bf.laneWaypoints[SIDE_BOTTOM][lane][i].v.y <
                   bf.laneWaypoints[SIDE_BOTTOM][lane][i - 1].v.y);
        }
    }
}

/* ---- CORE-01b: Center lane has consistent lateral position ---- */
static void test_center_lane_consistent_x(void) {
    Battlefield bf = make_test_battlefield();

    float centerX = bf.laneWaypoints[SIDE_BOTTOM][1][0].v.x;
    for (int i = 1; i < LANE_WAYPOINT_COUNT; i++) {
        assert(approx_eq(bf.laneWaypoints[SIDE_BOTTOM][1][i].v.x, centerX, 0.1f));
    }
}

/* ---- CORE-01d: Movement stepping advances waypointIndex ---- */
static void test_movement_step_advances_waypoint(void) {
    Battlefield bf = make_test_battlefield();

    /* Entity starts at waypoint[1] position -- large dt to guarantee overshoot */
    Entity e = make_test_entity(1, 1, 50000.0f);
    e.position = bf.laneWaypoints[SIDE_BOTTOM][1][1].v;

    bool walking = pathfind_step_entity(&e, &bf, 1.0f);
    (void)walking;
    /* Should have advanced past waypoint 1 */
    assert(e.waypointIndex >= 2);

    /* Normal speed: entity moves toward target but doesn't overshoot */
    Entity e2 = make_test_entity(1, 1, 10.0f); /* slow speed */
    e2.position = bf.laneWaypoints[SIDE_BOTTOM][1][1].v;
    /* Move slightly off the waypoint so there's distance to cover */
    e2.position.y += 50.0f;

    int prevIdx = e2.waypointIndex;
    pathfind_step_entity(&e2, &bf, 1.0f / 60.0f);
    /* With slow speed and 50px distance, should still be on same waypoint */
    assert(e2.waypointIndex == prevIdx);
}

/* ---- CORE-01e: Idle at last waypoint ---- */
static void test_idle_at_last_waypoint(void) {
    Battlefield bf = make_test_battlefield();

    /* Place entity near last waypoint with high speed + large dt to guarantee overshoot */
    Entity e = make_test_entity(1, LANE_WAYPOINT_COUNT - 1, 50000.0f);
    e.position = bf.laneWaypoints[SIDE_BOTTOM][1][LANE_WAYPOINT_COUNT - 2].v;

    bool walking = pathfind_step_entity(&e, &bf, 1.0f);

    /* Should have reached end and transitioned to idle */
    assert(walking == false);
    assert(e.state == ESTATE_IDLE);
    assert(e.waypointIndex >= LANE_WAYPOINT_COUNT);
}

/* ---- CORE-01f: Sprite direction from movement vector ---- */
static void test_sprite_direction(void) {
    AnimState anim;
    memset(&anim, 0, sizeof(AnimState));

    /* Moving left -> DIR_SIDE, flipH=true */
    anim.dir = DIR_UP;
    pathfind_apply_direction(&anim, (Vector2){-100, -10});
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == true);

    /* Moving right -> DIR_SIDE, flipH=false */
    pathfind_apply_direction(&anim, (Vector2){100, -10});
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == false);

    /* Moving up (negative Y) -> DIR_UP */
    pathfind_apply_direction(&anim, (Vector2){0, -100});
    assert(anim.dir == DIR_UP);
    assert(anim.flipH == false);

    /* Moving down (positive Y) -> DIR_DOWN */
    pathfind_apply_direction(&anim, (Vector2){0, 100});
    assert(anim.dir == DIR_DOWN);
    assert(anim.flipH == false);

    /* Zero vector: direction unchanged */
    anim.dir = DIR_UP;
    anim.flipH = false;
    pathfind_apply_direction(&anim, (Vector2){0, 0});
    assert(anim.dir == DIR_UP);

    /* Any nonzero X produces DIR_SIDE */
    memset(&anim, 0, sizeof(AnimState));
    pathfind_apply_direction(&anim, (Vector2){-1, -100});
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == true);
}

/* ---- CORE-01g: Perspective-aware vertical direction by owner side ---- */
static void test_sprite_direction_for_side(void) {
    AnimState anim;
    memset(&anim, 0, sizeof(AnimState));

    pathfind_apply_direction_for_side(&anim, (Vector2){100, 0}, SIDE_BOTTOM);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == false);

    pathfind_apply_direction_for_side(&anim, (Vector2){-100, 0}, SIDE_BOTTOM);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == true);

    pathfind_apply_direction_for_side(&anim, (Vector2){0, -100}, SIDE_BOTTOM);
    assert(anim.dir == DIR_UP);
    assert(anim.flipH == false);

    pathfind_apply_direction_for_side(&anim, (Vector2){0, 100}, SIDE_BOTTOM);
    assert(anim.dir == DIR_DOWN);
    assert(anim.flipH == false);

    // Top-side units walking down the canonical board are moving away from their
    // home camera, so they should use the back-facing row.
    pathfind_apply_direction_for_side(&anim, (Vector2){0, 100}, SIDE_TOP);
    assert(anim.dir == DIR_UP);
    assert(anim.flipH == false);

    pathfind_apply_direction_for_side(&anim, (Vector2){0, -100}, SIDE_TOP);
    assert(anim.dir == DIR_DOWN);
    assert(anim.flipH == false);

    pathfind_apply_direction_for_side(&anim, (Vector2){100, 0}, SIDE_TOP);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == true);

    pathfind_apply_direction_for_side(&anim, (Vector2){-100, 0}, SIDE_TOP);
    assert(anim.dir == DIR_SIDE);
    assert(anim.flipH == false);
}

/* ---- CORE-01ga: Presentation swaps once the entity crosses the seam ---- */
static void test_presentation_side_for_position(void) {
    assert(pathfind_presentation_side_for_position((Vector2){540.0f, 959.0f}, SEAM_Y) == SIDE_TOP);
    assert(pathfind_presentation_side_for_position((Vector2){540.0f, 960.0f}, SEAM_Y) == SIDE_BOTTOM);
    assert(pathfind_presentation_side_for_position((Vector2){540.0f, 1200.0f}, SEAM_Y) == SIDE_BOTTOM);
}

/* ---- CORE-01h: All top-side sprites rotate 180 degrees ---- */
static void test_sprite_rotation_for_side(void) {
    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_SIDE, SIDE_BOTTOM), 0.0f, 0.001f));
    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_UP, SIDE_BOTTOM), 0.0f, 0.001f));
    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_DOWN, SIDE_BOTTOM), 0.0f, 0.001f));

    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_SIDE, SIDE_TOP), 180.0f, 0.001f));
    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_UP, SIDE_TOP), 180.0f, 0.001f));
    assert(approx_eq(pathfind_sprite_rotation_for_side(DIR_DOWN, SIDE_TOP), 180.0f, 0.001f));
}

/* ---- CORE-01i: Seam overlap preserves previous presentation side ---- */
static void test_seam_overlap_preserves_presentation_bottom_to_top(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.position = (Vector2){ bf.laneWaypoints[SIDE_BOTTOM][1][4].v.x, 965.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    assert(e.position.y < SEAM_Y);
    assert(e.position.y + 32.0f > SEAM_Y);
    assert(e.presentationSide == SIDE_BOTTOM);
    assert(e.anim.dir == DIR_UP);
    assert(e.anim.flipH == false);
    assert(approx_eq(e.spriteRotationDegrees, 0.0f, 0.001f));
}

/* ---- CORE-01j: Fully clear still defers until a walk-loop commit ---- */
static void test_seam_clear_defers_presentation_bottom_to_top(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.position = (Vector2){ bf.laneWaypoints[SIDE_BOTTOM][1][4].v.x, 915.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    assert(e.position.y + 32.0f < SEAM_Y);
    assert(e.presentationSide == SIDE_BOTTOM);
    assert(e.anim.dir == DIR_UP);
    assert(e.anim.flipH == false);
    assert(approx_eq(e.spriteRotationDegrees, 0.0f, 0.001f));
}

/* ---- CORE-01k: Walk-loop commit applies bottom-to-top presentation swap ---- */
static void test_walk_loop_commit_swaps_presentation_bottom_to_top(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.position = (Vector2){ bf.laneWaypoints[SIDE_BOTTOM][1][4].v.x, 915.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    pathfind_commit_presentation(&e, &bf);
    pathfind_update_walk_facing(&e, &bf);

    assert(e.presentationSide == SIDE_TOP);
    assert(e.anim.dir == DIR_DOWN);
    assert(e.anim.flipH == false);
    assert(approx_eq(e.spriteRotationDegrees, 180.0f, 0.001f));
}

/* ---- CORE-01l: Seam overlap preserves top-side presentation too ---- */
static void test_seam_overlap_preserves_presentation_top_to_bottom(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.ownerID = 1;
    e.presentationSide = SIDE_TOP;
    e.position = (Vector2){ bf.laneWaypoints[SIDE_TOP][1][4].v.x, 955.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    assert(e.position.y > SEAM_Y);
    assert(e.position.y - 32.0f < SEAM_Y);
    assert(e.presentationSide == SIDE_TOP);
    assert(e.anim.dir == DIR_UP);
    assert(e.anim.flipH == false);
    assert(approx_eq(e.spriteRotationDegrees, 180.0f, 0.001f));
}

/* ---- CORE-01m: Fully clear still defers top-to-bottom swap until commit ---- */
static void test_seam_clear_defers_presentation_top_to_bottom(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.ownerID = 1;
    e.presentationSide = SIDE_TOP;
    e.position = (Vector2){ bf.laneWaypoints[SIDE_TOP][1][4].v.x, 1005.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    assert(e.position.y - 32.0f > SEAM_Y);
    assert(e.presentationSide == SIDE_TOP);
    assert(e.anim.dir == DIR_UP);
    assert(e.anim.flipH == false);
    assert(approx_eq(e.spriteRotationDegrees, 180.0f, 0.001f));
}

/* ---- CORE-01n: Walk-loop commit applies top-to-bottom presentation swap ---- */
static void test_walk_loop_commit_swaps_presentation_top_to_bottom(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(1, 4, 600.0f);
    e.ownerID = 1;
    e.presentationSide = SIDE_TOP;
    e.position = (Vector2){ bf.laneWaypoints[SIDE_TOP][1][4].v.x, 1005.0f };

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == true);
    pathfind_commit_presentation(&e, &bf);
    pathfind_update_walk_facing(&e, &bf);

    assert(e.presentationSide == SIDE_BOTTOM);
    assert(e.anim.dir == DIR_DOWN);
    assert(e.anim.flipH == false);
    assert(approx_eq(e.spriteRotationDegrees, 0.0f, 0.001f));
}

/* ---- CORE-01 bonus: Invalid lane produces IDLE ---- */
static void test_invalid_lane_idles(void) {
    Battlefield bf = make_test_battlefield();

    Entity e = make_test_entity(-1, 1, 100.0f);
    e.position = (Vector2){500, 1500};

    bool walking = pathfind_step_entity(&e, &bf, 1.0f / 60.0f);
    assert(walking == false);
    assert(e.state == ESTATE_IDLE);

    Entity e2 = make_test_entity(3, 1, 100.0f);
    e2.position = (Vector2){500, 1500};
    walking = pathfind_step_entity(&e2, &bf, 1.0f / 60.0f);
    assert(walking == false);
    assert(e2.state == ESTATE_IDLE);
}

/* ---- main ---- */
int main(void) {
    printf("Running pathfinding tests...\n");
    test_canonical_waypoints_progress();         printf("  PASS: test_canonical_waypoints_progress\n");
    test_center_lane_consistent_x();             printf("  PASS: test_center_lane_consistent_x\n");
    test_movement_step_advances_waypoint();       printf("  PASS: test_movement_step_advances_waypoint\n");
    test_idle_at_last_waypoint();                 printf("  PASS: test_idle_at_last_waypoint\n");
    test_sprite_direction();                      printf("  PASS: test_sprite_direction\n");
    test_sprite_direction_for_side();             printf("  PASS: test_sprite_direction_for_side\n");
    test_presentation_side_for_position();        printf("  PASS: test_presentation_side_for_position\n");
    test_sprite_rotation_for_side();              printf("  PASS: test_sprite_rotation_for_side\n");
    test_seam_overlap_preserves_presentation_bottom_to_top();
    printf("  PASS: test_seam_overlap_preserves_presentation_bottom_to_top\n");
    test_seam_clear_defers_presentation_bottom_to_top();
    printf("  PASS: test_seam_clear_defers_presentation_bottom_to_top\n");
    test_walk_loop_commit_swaps_presentation_bottom_to_top();
    printf("  PASS: test_walk_loop_commit_swaps_presentation_bottom_to_top\n");
    test_seam_overlap_preserves_presentation_top_to_bottom();
    printf("  PASS: test_seam_overlap_preserves_presentation_top_to_bottom\n");
    test_seam_clear_defers_presentation_top_to_bottom();
    printf("  PASS: test_seam_clear_defers_presentation_top_to_bottom\n");
    test_walk_loop_commit_swaps_presentation_top_to_bottom();
    printf("  PASS: test_walk_loop_commit_swaps_presentation_top_to_bottom\n");
    test_invalid_lane_idles();                    printf("  PASS: test_invalid_lane_idles\n");
    printf("\nAll 15 tests passed!\n");
    return 0;
}
