#!/usr/bin/env python3

from pathlib import Path
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/rendering/sprite_frame_atlas.h"
DIR_COUNT = 3

SHEETS = [
    ("base_basic_idle", "src/assets/characters/Base/Basic/idle.png", 4),
    ("base_basic_run", "src/assets/characters/Base/Basic/run.png", 8),
    ("base_basic_walk", "src/assets/characters/Base/Basic/walk.png", 8),
    ("base_basic_hurt", "src/assets/characters/Base/Basic/hurt.png", 4),
    ("base_basic_death", "src/assets/characters/Base/Basic/death.png", 6),
    ("base_attack_sword", "src/assets/characters/Base/Attack/sword.png", 6),
    ("knight_idle", "src/assets/characters/Knight/idle.png", 4),
    ("knight_walk", "src/assets/characters/Knight/walk.png", 8),
    ("knight_run", "src/assets/characters/Knight/run.png", 8),
    ("knight_hurt", "src/assets/characters/Knight/hurt.png", 4),
    ("knight_death", "src/assets/characters/Knight/death.png", 6),
    ("knight_attack", "src/assets/characters/Knight/sword.png", 6),
    ("healer_idle", "src/assets/characters/Healer/idle.png", 4),
    ("healer_walk", "src/assets/characters/Healer/walk.png", 8),
    ("healer_run", "src/assets/characters/Healer/run.png", 8),
    ("healer_hurt", "src/assets/characters/Healer/hurt.png", 4),
    ("healer_death", "src/assets/characters/Healer/death.png", 6),
    ("healer_attack", "src/assets/characters/Healer/staff.png", 10),
    ("assassin_idle", "src/assets/characters/Assassin/idle.png", 4),
    ("assassin_walk", "src/assets/characters/Assassin/walk.png", 8),
    ("assassin_run", "src/assets/characters/Assassin/run.png", 8),
    ("assassin_hurt", "src/assets/characters/Assassin/hurt.png", 4),
    ("assassin_death", "src/assets/characters/Assassin/death.png", 6),
    ("assassin_attack", "src/assets/characters/Assassin/sword 2.png", 6),
    ("brute_idle", "src/assets/characters/Brute/idle.png", 4),
    ("brute_walk", "src/assets/characters/Brute/walk.png", 8),
    ("brute_run", "src/assets/characters/Brute/run.png", 8),
    ("brute_hurt", "src/assets/characters/Brute/hurt.png", 4),
    ("brute_death", "src/assets/characters/Brute/death.png", 6),
    ("brute_attack", "src/assets/characters/Brute/block.png", 4),
    ("farmer_idle", "src/assets/characters/Farmer/idle.png", 4),
    ("farmer_walk", "src/assets/characters/Farmer/walk.png", 8),
    ("farmer_run", "src/assets/characters/Farmer/run.png", 8),
    ("farmer_hurt", "src/assets/characters/Farmer/hurt.png", 4),
    ("farmer_death", "src/assets/characters/Farmer/death.png", 6),
    ("farmer_attack", "src/assets/characters/Farmer/pickaxe.png", 6),
]


def compute_bounds(path: str, frame_count: int):
    image = Image.open(ROOT / path).convert("RGBA")
    frame_width = image.width // frame_count
    frame_height = image.height // DIR_COUNT
    alpha = image.getchannel("A")
    bounds = []

    for row in range(DIR_COUNT):
        for col in range(frame_count):
            left = col * frame_width
            top = row * frame_height
            bbox = alpha.crop((left, top, left + frame_width, top + frame_height)).getbbox()
            if bbox is None:
                bounds.append((0, 0, 0, 0))
                continue

            x0, y0, x1, y1 = bbox
            bounds.append((x0, y0, x1 - x0, y1 - y0))

    return bounds


def rect_line(rect):
    x, y, w, h = rect
    return f"    {{ {x:.1f}f, {y:.1f}f, {w:.1f}f, {h:.1f}f }},"


def main():
    lines = []
    lines.append("// Generated by tools/generate_sprite_frame_atlas.py")
    lines.append("// Do not edit by hand.")
    lines.append("")
    lines.append("#ifndef NFC_CARDGAME_SPRITE_FRAME_ATLAS_H")
    lines.append("#define NFC_CARDGAME_SPRITE_FRAME_ATLAS_H")
    lines.append("")

    for name, path, frame_count in SHEETS:
        bounds = compute_bounds(path, frame_count)
        lines.append(f"static const Rectangle s_{name}_bounds[] = {{")
        lines.extend(rect_line(rect) for rect in bounds)
        lines.append("};")
        lines.append("")

    lines.append("static const SpriteSheetAtlasEntry kSpriteSheetAtlas[] = {")
    for name, path, frame_count in SHEETS:
        lines.append(f'    {{ "{path}", {frame_count}, s_{name}_bounds }},')
    lines.append("};")
    lines.append("")
    lines.append(
        "static const int kSpriteSheetAtlasCount = "
        "(int) (sizeof(kSpriteSheetAtlas) / sizeof(kSpriteSheetAtlas[0]));"
    )
    lines.append("")
    lines.append("#endif // NFC_CARDGAME_SPRITE_FRAME_ATLAS_H")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="ascii")


if __name__ == "__main__":
    main()
