#!/usr/bin/env python3

import re
from pathlib import Path
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/rendering/sprite_frame_atlas.h"
DIR_COUNT = 3
MANIFEST = ROOT / "src/rendering/sprite_sheet_manifest.def"
ENTRY_RE = re.compile(
    r'^SPRITE_SHEET\('
    r'\s*([A-Za-z0-9_]+)\s*,'
    r'\s*(true|false)\s*,'
    r'\s*([A-Za-z0-9_]+)\s*,'
    r'\s*([A-Za-z0-9_]+)\s*,'
    r'\s*"([^"]+)"\s*,'
    r'\s*(\d+)\s*,'
    r'\s*(\d+)\s*,'
    r'\s*(\d+)\s*,'
    r'\s*(true|false)\s*'
    r'\)$'
)


def manifest_entries():
    entries = []
    for lineno, raw_line in enumerate(MANIFEST.read_text(encoding="ascii").splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("//"):
            continue

        match = ENTRY_RE.match(line)
        if not match:
            raise ValueError(f"Unsupported manifest syntax at {MANIFEST}:{lineno}: {raw_line}")

        name, _is_base_fallback, _sprite_type, _anim, path, frame_count, source_row_count, frames_per_row, required = match.groups()
        entries.append({
            "name": name,
            "path": path,
            "frame_count": int(frame_count),
            "source_row_count": int(source_row_count),
            "frames_per_row": int(frames_per_row),
            "required": (required == "true"),
        })

    return entries


def compute_bounds(path: str, frame_count: int, source_row_count: int, frames_per_row: int):
    image = Image.open(ROOT / path).convert("RGBA")
    source_row_count = max(1, source_row_count)
    frames_per_row = max(1, min(frame_count, frames_per_row))
    rows_per_direction = (frame_count + frames_per_row - 1) // frames_per_row
    total_row_count = source_row_count * rows_per_direction
    if image.height % total_row_count != 0:
        raise ValueError(
            f"{path} height {image.height} is not divisible by total row count {total_row_count}"
        )
    if image.width % frames_per_row != 0:
        raise ValueError(
            f"{path} width {image.width} is not divisible by frame columns {frames_per_row}"
        )

    frame_width = image.width // frames_per_row
    frame_height = image.height // total_row_count
    alpha = image.getchannel("A")
    bounds = []

    for row in range(DIR_COUNT):
        source_row = min(row, source_row_count - 1)
        for col in range(frame_count):
            left = (col % frames_per_row) * frame_width
            top = (source_row * rows_per_direction + (col // frames_per_row)) * frame_height
            bbox = alpha.crop((left, top, left + frame_width, top + frame_height)).getbbox()
            if bbox is None:
                bounds.append((0, 0, 0, 0))
                continue

            x0, y0, x1, y1 = bbox
            bounds.append((x0, y0, x1 - x0, y1 - y0))

    return bounds


def rect_line(rect):
    x, y, w, h = rect
    return f"    {{ {x:.1f}f, {y:.1f}f, {w:.1f}f, {h:.1f}f }},"


def main():
    entries = []
    for entry in manifest_entries():
        if not (ROOT / entry["path"]).exists():
            if entry["required"]:
                raise FileNotFoundError(f"Missing required sprite sheet: {entry['path']}")
            print(f"Skipping optional sprite sheet: {entry['path']}")
            continue
        entries.append(entry)

    lines = []
    lines.append("// Generated by tools/generate_sprite_frame_atlas.py")
    lines.append("// Do not edit by hand.")
    lines.append("")
    lines.append("#ifndef NFC_CARDGAME_SPRITE_FRAME_ATLAS_H")
    lines.append("#define NFC_CARDGAME_SPRITE_FRAME_ATLAS_H")
    lines.append("")

    for entry in entries:
        bounds = compute_bounds(entry["path"], entry["frame_count"],
                                entry["source_row_count"], entry["frames_per_row"])
        name = entry["name"]
        lines.append(f"static const Rectangle s_{name}_bounds[] = {{")
        lines.extend(rect_line(rect) for rect in bounds)
        lines.append("};")
        lines.append("")

    lines.append("static const SpriteSheetAtlasEntry kSpriteSheetAtlas[] = {")
    for entry in entries:
        lines.append(
            f'    {{ "{entry["path"]}", {entry["frame_count"]}, '
            f'{entry["source_row_count"]}, {entry["frames_per_row"]}, s_{entry["name"]}_bounds }},'
        )
    lines.append("};")
    lines.append("")
    lines.append(
        "static const int kSpriteSheetAtlasCount = "
        "(int) (sizeof(kSpriteSheetAtlas) / sizeof(kSpriteSheetAtlas[0]));"
    )
    lines.append("")
    lines.append("#endif // NFC_CARDGAME_SPRITE_FRAME_ATLAS_H")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="ascii")


if __name__ == "__main__":
    main()
